// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_log.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const countAdminLogs = `-- name: CountAdminLogs :one

SELECT COUNT(*) FROM admin_logs
`

// =============================================
// 3. 日志统计 (Log Statistics)
// =============================================
// 统计日志总数
func (q *Queries) CountAdminLogs(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countAdminLogsStmt, countAdminLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminLogsByOperator = `-- name: CountAdminLogsByOperator :one
SELECT COUNT(*) FROM admin_logs WHERE operator_user_id = $1
`

// 统计操作员的日志数
func (q *Queries) CountAdminLogsByOperator(ctx context.Context, operatorUserID sql.NullString) (int64, error) {
	row := q.queryRow(ctx, q.countAdminLogsByOperatorStmt, countAdminLogsByOperator, operatorUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminLogsByRoom = `-- name: CountAdminLogsByRoom :one
SELECT COUNT(*) FROM admin_logs WHERE related_room_id = $1
`

// 统计聊天室的日志数
func (q *Queries) CountAdminLogsByRoom(ctx context.Context, relatedRoomID sql.NullString) (int64, error) {
	row := q.queryRow(ctx, q.countAdminLogsByRoomStmt, countAdminLogsByRoom, relatedRoomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminLogsByType = `-- name: CountAdminLogsByType :one
SELECT COUNT(*) FROM admin_logs WHERE operation_type = $1
`

// 按类型统计日志数
func (q *Queries) CountAdminLogsByType(ctx context.Context, operationType string) (int64, error) {
	row := q.queryRow(ctx, q.countAdminLogsByTypeStmt, countAdminLogsByType, operationType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminLog = `-- name: CreateAdminLog :one


INSERT INTO admin_logs (
    operator_user_id,
    operation_type,
    reason,
    details,
    is_global,
    related_room_id,
    related_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING 
    log_id,
    operator_user_id,
    operated_at,
    operation_type,
    reason,
    details,
    is_global,
    related_room_id,
    related_user_id
`

type CreateAdminLogParams struct {
	OperatorUserID sql.NullString        `json:"operator_user_id"`
	OperationType  string                `json:"operation_type"`
	Reason         sql.NullString        `json:"reason"`
	Details        pqtype.NullRawMessage `json:"details"`
	IsGlobal       bool                  `json:"is_global"`
	RelatedRoomID  sql.NullString        `json:"related_room_id"`
	RelatedUserID  sql.NullString        `json:"related_user_id"`
}

// =============================================
// 管理操作日志相关SQL查询 (Admin Log Queries)
// 对应API: 系统管理接口
// =============================================
// =============================================
// 1. 日志创建 (Log Creation)
// =============================================
// 创建管理操作日志
func (q *Queries) CreateAdminLog(ctx context.Context, arg CreateAdminLogParams) (AdminLog, error) {
	row := q.queryRow(ctx, q.createAdminLogStmt, createAdminLog,
		arg.OperatorUserID,
		arg.OperationType,
		arg.Reason,
		arg.Details,
		arg.IsGlobal,
		arg.RelatedRoomID,
		arg.RelatedUserID,
	)
	var i AdminLog
	err := row.Scan(
		&i.LogID,
		&i.OperatorUserID,
		&i.OperatedAt,
		&i.OperationType,
		&i.Reason,
		&i.Details,
		&i.IsGlobal,
		&i.RelatedRoomID,
		&i.RelatedUserID,
	)
	return i, err
}

const createBanLog = `-- name: CreateBanLog :one
INSERT INTO admin_logs (
    operator_user_id,
    operation_type,
    reason,
    details,
    is_global,
    related_room_id,
    related_user_id
) VALUES (
    $1, 'ban', $2, $3, true, NULL, $4
) RETURNING 
    log_id,
    operator_user_id,
    operated_at,
    operation_type,
    reason,
    details,
    is_global,
    related_room_id,
    related_user_id
`

type CreateBanLogParams struct {
	OperatorUserID sql.NullString        `json:"operator_user_id"`
	Reason         sql.NullString        `json:"reason"`
	Details        pqtype.NullRawMessage `json:"details"`
	RelatedUserID  sql.NullString        `json:"related_user_id"`
}

// 创建封禁账号操作日志
func (q *Queries) CreateBanLog(ctx context.Context, arg CreateBanLogParams) (AdminLog, error) {
	row := q.queryRow(ctx, q.createBanLogStmt, createBanLog,
		arg.OperatorUserID,
		arg.Reason,
		arg.Details,
		arg.RelatedUserID,
	)
	var i AdminLog
	err := row.Scan(
		&i.LogID,
		&i.OperatorUserID,
		&i.OperatedAt,
		&i.OperationType,
		&i.Reason,
		&i.Details,
		&i.IsGlobal,
		&i.RelatedRoomID,
		&i.RelatedUserID,
	)
	return i, err
}

const createDeleteMessageLog = `-- name: CreateDeleteMessageLog :one
INSERT INTO admin_logs (
    operator_user_id,
    operation_type,
    reason,
    details,
    is_global,
    related_room_id,
    related_user_id
) VALUES (
    $1, 'delete_message', $2, $3, false, $4, $5
) RETURNING 
    log_id,
    operator_user_id,
    operated_at,
    operation_type,
    reason,
    details,
    is_global,
    related_room_id,
    related_user_id
`

type CreateDeleteMessageLogParams struct {
	OperatorUserID sql.NullString        `json:"operator_user_id"`
	Reason         sql.NullString        `json:"reason"`
	Details        pqtype.NullRawMessage `json:"details"`
	RelatedRoomID  sql.NullString        `json:"related_room_id"`
	RelatedUserID  sql.NullString        `json:"related_user_id"`
}

// 创建删除消息操作日志
func (q *Queries) CreateDeleteMessageLog(ctx context.Context, arg CreateDeleteMessageLogParams) (AdminLog, error) {
	row := q.queryRow(ctx, q.createDeleteMessageLogStmt, createDeleteMessageLog,
		arg.OperatorUserID,
		arg.Reason,
		arg.Details,
		arg.RelatedRoomID,
		arg.RelatedUserID,
	)
	var i AdminLog
	err := row.Scan(
		&i.LogID,
		&i.OperatorUserID,
		&i.OperatedAt,
		&i.OperationType,
		&i.Reason,
		&i.Details,
		&i.IsGlobal,
		&i.RelatedRoomID,
		&i.RelatedUserID,
	)
	return i, err
}

const createKickLog = `-- name: CreateKickLog :one
INSERT INTO admin_logs (
    operator_user_id,
    operation_type,
    reason,
    details,
    is_global,
    related_room_id,
    related_user_id
) VALUES (
    $1, 'kick', $2, $3, false, $4, $5
) RETURNING 
    log_id,
    operator_user_id,
    operated_at,
    operation_type,
    reason,
    details,
    is_global,
    related_room_id,
    related_user_id
`

type CreateKickLogParams struct {
	OperatorUserID sql.NullString        `json:"operator_user_id"`
	Reason         sql.NullString        `json:"reason"`
	Details        pqtype.NullRawMessage `json:"details"`
	RelatedRoomID  sql.NullString        `json:"related_room_id"`
	RelatedUserID  sql.NullString        `json:"related_user_id"`
}

// 创建踢人操作日志
func (q *Queries) CreateKickLog(ctx context.Context, arg CreateKickLogParams) (AdminLog, error) {
	row := q.queryRow(ctx, q.createKickLogStmt, createKickLog,
		arg.OperatorUserID,
		arg.Reason,
		arg.Details,
		arg.RelatedRoomID,
		arg.RelatedUserID,
	)
	var i AdminLog
	err := row.Scan(
		&i.LogID,
		&i.OperatorUserID,
		&i.OperatedAt,
		&i.OperationType,
		&i.Reason,
		&i.Details,
		&i.IsGlobal,
		&i.RelatedRoomID,
		&i.RelatedUserID,
	)
	return i, err
}

const createMuteLog = `-- name: CreateMuteLog :one
INSERT INTO admin_logs (
    operator_user_id,
    operation_type,
    reason,
    details,
    is_global,
    related_room_id,
    related_user_id
) VALUES (
    $1, 'mute', $2, $3, $4, $5, $6
) RETURNING 
    log_id,
    operator_user_id,
    operated_at,
    operation_type,
    reason,
    details,
    is_global,
    related_room_id,
    related_user_id
`

type CreateMuteLogParams struct {
	OperatorUserID sql.NullString        `json:"operator_user_id"`
	Reason         sql.NullString        `json:"reason"`
	Details        pqtype.NullRawMessage `json:"details"`
	IsGlobal       bool                  `json:"is_global"`
	RelatedRoomID  sql.NullString        `json:"related_room_id"`
	RelatedUserID  sql.NullString        `json:"related_user_id"`
}

// 创建禁言操作日志
func (q *Queries) CreateMuteLog(ctx context.Context, arg CreateMuteLogParams) (AdminLog, error) {
	row := q.queryRow(ctx, q.createMuteLogStmt, createMuteLog,
		arg.OperatorUserID,
		arg.Reason,
		arg.Details,
		arg.IsGlobal,
		arg.RelatedRoomID,
		arg.RelatedUserID,
	)
	var i AdminLog
	err := row.Scan(
		&i.LogID,
		&i.OperatorUserID,
		&i.OperatedAt,
		&i.OperationType,
		&i.Reason,
		&i.Details,
		&i.IsGlobal,
		&i.RelatedRoomID,
		&i.RelatedUserID,
	)
	return i, err
}

const createRoleChangeLog = `-- name: CreateRoleChangeLog :one
INSERT INTO admin_logs (
    operator_user_id,
    operation_type,
    reason,
    details,
    is_global,
    related_room_id,
    related_user_id
) VALUES (
    $1, 'role_change', $2, $3, false, $4, $5
) RETURNING 
    log_id,
    operator_user_id,
    operated_at,
    operation_type,
    reason,
    details,
    is_global,
    related_room_id,
    related_user_id
`

type CreateRoleChangeLogParams struct {
	OperatorUserID sql.NullString        `json:"operator_user_id"`
	Reason         sql.NullString        `json:"reason"`
	Details        pqtype.NullRawMessage `json:"details"`
	RelatedRoomID  sql.NullString        `json:"related_room_id"`
	RelatedUserID  sql.NullString        `json:"related_user_id"`
}

// 创建角色变更操作日志
func (q *Queries) CreateRoleChangeLog(ctx context.Context, arg CreateRoleChangeLogParams) (AdminLog, error) {
	row := q.queryRow(ctx, q.createRoleChangeLogStmt, createRoleChangeLog,
		arg.OperatorUserID,
		arg.Reason,
		arg.Details,
		arg.RelatedRoomID,
		arg.RelatedUserID,
	)
	var i AdminLog
	err := row.Scan(
		&i.LogID,
		&i.OperatorUserID,
		&i.OperatedAt,
		&i.OperationType,
		&i.Reason,
		&i.Details,
		&i.IsGlobal,
		&i.RelatedRoomID,
		&i.RelatedUserID,
	)
	return i, err
}

const createUnmuteLog = `-- name: CreateUnmuteLog :one
INSERT INTO admin_logs (
    operator_user_id,
    operation_type,
    reason,
    details,
    is_global,
    related_room_id,
    related_user_id
) VALUES (
    $1, 'unmute', $2, $3, $4, $5, $6
) RETURNING 
    log_id,
    operator_user_id,
    operated_at,
    operation_type,
    reason,
    details,
    is_global,
    related_room_id,
    related_user_id
`

type CreateUnmuteLogParams struct {
	OperatorUserID sql.NullString        `json:"operator_user_id"`
	Reason         sql.NullString        `json:"reason"`
	Details        pqtype.NullRawMessage `json:"details"`
	IsGlobal       bool                  `json:"is_global"`
	RelatedRoomID  sql.NullString        `json:"related_room_id"`
	RelatedUserID  sql.NullString        `json:"related_user_id"`
}

// 创建解除禁言操作日志
func (q *Queries) CreateUnmuteLog(ctx context.Context, arg CreateUnmuteLogParams) (AdminLog, error) {
	row := q.queryRow(ctx, q.createUnmuteLogStmt, createUnmuteLog,
		arg.OperatorUserID,
		arg.Reason,
		arg.Details,
		arg.IsGlobal,
		arg.RelatedRoomID,
		arg.RelatedUserID,
	)
	var i AdminLog
	err := row.Scan(
		&i.LogID,
		&i.OperatorUserID,
		&i.OperatedAt,
		&i.OperationType,
		&i.Reason,
		&i.Details,
		&i.IsGlobal,
		&i.RelatedRoomID,
		&i.RelatedUserID,
	)
	return i, err
}

const getAdminLogByID = `-- name: GetAdminLogByID :one

SELECT 
    log_id,
    operator_user_id,
    operated_at,
    operation_type,
    reason,
    details,
    is_global,
    related_room_id,
    related_user_id
FROM admin_logs 
WHERE log_id = $1
`

// =============================================
// 2. 日志查询 (Log Queries)
// =============================================
// 获取单条日志
func (q *Queries) GetAdminLogByID(ctx context.Context, logID string) (AdminLog, error) {
	row := q.queryRow(ctx, q.getAdminLogByIDStmt, getAdminLogByID, logID)
	var i AdminLog
	err := row.Scan(
		&i.LogID,
		&i.OperatorUserID,
		&i.OperatedAt,
		&i.OperationType,
		&i.Reason,
		&i.Details,
		&i.IsGlobal,
		&i.RelatedRoomID,
		&i.RelatedUserID,
	)
	return i, err
}

const getAdminLogStats = `-- name: GetAdminLogStats :many
SELECT 
    operation_type,
    COUNT(*) AS count
FROM admin_logs
GROUP BY operation_type
ORDER BY count DESC
`

type GetAdminLogStatsRow struct {
	OperationType string `json:"operation_type"`
	Count         int64  `json:"count"`
}

// 获取各类型操作的统计
func (q *Queries) GetAdminLogStats(ctx context.Context) ([]GetAdminLogStatsRow, error) {
	rows, err := q.query(ctx, q.getAdminLogStatsStmt, getAdminLogStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminLogStatsRow{}
	for rows.Next() {
		var i GetAdminLogStatsRow
		if err := rows.Scan(&i.OperationType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminLogs = `-- name: GetAdminLogs :many
SELECT 
    al.log_id,
    al.operator_user_id,
    al.operated_at,
    al.operation_type,
    al.reason,
    al.details,
    al.is_global,
    al.related_room_id,
    al.related_user_id,
    ou.username AS operator_username,
    ou.nickname AS operator_nickname,
    ru.username AS related_username,
    ru.nickname AS related_nickname
FROM admin_logs al
LEFT JOIN users ou ON al.operator_user_id = ou.user_id
LEFT JOIN users ru ON al.related_user_id = ru.user_id
ORDER BY al.operated_at DESC
LIMIT $1 OFFSET $2
`

type GetAdminLogsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type GetAdminLogsRow struct {
	LogID            string                `json:"log_id"`
	OperatorUserID   sql.NullString        `json:"operator_user_id"`
	OperatedAt       time.Time             `json:"operated_at"`
	OperationType    string                `json:"operation_type"`
	Reason           sql.NullString        `json:"reason"`
	Details          pqtype.NullRawMessage `json:"details"`
	IsGlobal         bool                  `json:"is_global"`
	RelatedRoomID    sql.NullString        `json:"related_room_id"`
	RelatedUserID    sql.NullString        `json:"related_user_id"`
	OperatorUsername sql.NullString        `json:"operator_username"`
	OperatorNickname sql.NullString        `json:"operator_nickname"`
	RelatedUsername  sql.NullString        `json:"related_username"`
	RelatedNickname  sql.NullString        `json:"related_nickname"`
}

// 获取所有管理日志（分页）
func (q *Queries) GetAdminLogs(ctx context.Context, arg GetAdminLogsParams) ([]GetAdminLogsRow, error) {
	rows, err := q.query(ctx, q.getAdminLogsStmt, getAdminLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminLogsRow{}
	for rows.Next() {
		var i GetAdminLogsRow
		if err := rows.Scan(
			&i.LogID,
			&i.OperatorUserID,
			&i.OperatedAt,
			&i.OperationType,
			&i.Reason,
			&i.Details,
			&i.IsGlobal,
			&i.RelatedRoomID,
			&i.RelatedUserID,
			&i.OperatorUsername,
			&i.OperatorNickname,
			&i.RelatedUsername,
			&i.RelatedNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminLogsByOperator = `-- name: GetAdminLogsByOperator :many
SELECT 
    al.log_id,
    al.operator_user_id,
    al.operated_at,
    al.operation_type,
    al.reason,
    al.details,
    al.is_global,
    al.related_room_id,
    al.related_user_id,
    ru.username AS related_username,
    ru.nickname AS related_nickname
FROM admin_logs al
LEFT JOIN users ru ON al.related_user_id = ru.user_id
WHERE al.operator_user_id = $1
ORDER BY al.operated_at DESC
LIMIT $2 OFFSET $3
`

type GetAdminLogsByOperatorParams struct {
	OperatorUserID sql.NullString `json:"operator_user_id"`
	Limit          int64          `json:"limit"`
	Offset         int64          `json:"offset"`
}

type GetAdminLogsByOperatorRow struct {
	LogID           string                `json:"log_id"`
	OperatorUserID  sql.NullString        `json:"operator_user_id"`
	OperatedAt      time.Time             `json:"operated_at"`
	OperationType   string                `json:"operation_type"`
	Reason          sql.NullString        `json:"reason"`
	Details         pqtype.NullRawMessage `json:"details"`
	IsGlobal        bool                  `json:"is_global"`
	RelatedRoomID   sql.NullString        `json:"related_room_id"`
	RelatedUserID   sql.NullString        `json:"related_user_id"`
	RelatedUsername sql.NullString        `json:"related_username"`
	RelatedNickname sql.NullString        `json:"related_nickname"`
}

// 获取指定操作员的日志
func (q *Queries) GetAdminLogsByOperator(ctx context.Context, arg GetAdminLogsByOperatorParams) ([]GetAdminLogsByOperatorRow, error) {
	rows, err := q.query(ctx, q.getAdminLogsByOperatorStmt, getAdminLogsByOperator, arg.OperatorUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminLogsByOperatorRow{}
	for rows.Next() {
		var i GetAdminLogsByOperatorRow
		if err := rows.Scan(
			&i.LogID,
			&i.OperatorUserID,
			&i.OperatedAt,
			&i.OperationType,
			&i.Reason,
			&i.Details,
			&i.IsGlobal,
			&i.RelatedRoomID,
			&i.RelatedUserID,
			&i.RelatedUsername,
			&i.RelatedNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminLogsByRoom = `-- name: GetAdminLogsByRoom :many
SELECT 
    al.log_id,
    al.operator_user_id,
    al.operated_at,
    al.operation_type,
    al.reason,
    al.details,
    al.is_global,
    al.related_room_id,
    al.related_user_id,
    ou.username AS operator_username,
    ou.nickname AS operator_nickname,
    ru.username AS related_username,
    ru.nickname AS related_nickname
FROM admin_logs al
LEFT JOIN users ou ON al.operator_user_id = ou.user_id
LEFT JOIN users ru ON al.related_user_id = ru.user_id
WHERE al.related_room_id = $1
ORDER BY al.operated_at DESC
LIMIT $2 OFFSET $3
`

type GetAdminLogsByRoomParams struct {
	RelatedRoomID sql.NullString `json:"related_room_id"`
	Limit         int64          `json:"limit"`
	Offset        int64          `json:"offset"`
}

type GetAdminLogsByRoomRow struct {
	LogID            string                `json:"log_id"`
	OperatorUserID   sql.NullString        `json:"operator_user_id"`
	OperatedAt       time.Time             `json:"operated_at"`
	OperationType    string                `json:"operation_type"`
	Reason           sql.NullString        `json:"reason"`
	Details          pqtype.NullRawMessage `json:"details"`
	IsGlobal         bool                  `json:"is_global"`
	RelatedRoomID    sql.NullString        `json:"related_room_id"`
	RelatedUserID    sql.NullString        `json:"related_user_id"`
	OperatorUsername sql.NullString        `json:"operator_username"`
	OperatorNickname sql.NullString        `json:"operator_nickname"`
	RelatedUsername  sql.NullString        `json:"related_username"`
	RelatedNickname  sql.NullString        `json:"related_nickname"`
}

// 获取聊天室的管理日志
func (q *Queries) GetAdminLogsByRoom(ctx context.Context, arg GetAdminLogsByRoomParams) ([]GetAdminLogsByRoomRow, error) {
	rows, err := q.query(ctx, q.getAdminLogsByRoomStmt, getAdminLogsByRoom, arg.RelatedRoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminLogsByRoomRow{}
	for rows.Next() {
		var i GetAdminLogsByRoomRow
		if err := rows.Scan(
			&i.LogID,
			&i.OperatorUserID,
			&i.OperatedAt,
			&i.OperationType,
			&i.Reason,
			&i.Details,
			&i.IsGlobal,
			&i.RelatedRoomID,
			&i.RelatedUserID,
			&i.OperatorUsername,
			&i.OperatorNickname,
			&i.RelatedUsername,
			&i.RelatedNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminLogsByTimeRange = `-- name: GetAdminLogsByTimeRange :many
SELECT 
    al.log_id,
    al.operator_user_id,
    al.operated_at,
    al.operation_type,
    al.reason,
    al.details,
    al.is_global,
    al.related_room_id,
    al.related_user_id,
    ou.username AS operator_username,
    ou.nickname AS operator_nickname,
    ru.username AS related_username,
    ru.nickname AS related_nickname
FROM admin_logs al
LEFT JOIN users ou ON al.operator_user_id = ou.user_id
LEFT JOIN users ru ON al.related_user_id = ru.user_id
WHERE al.operated_at >= $1 AND al.operated_at <= $2
ORDER BY al.operated_at DESC
LIMIT $3 OFFSET $4
`

type GetAdminLogsByTimeRangeParams struct {
	OperatedAt   time.Time `json:"operated_at"`
	OperatedAt_2 time.Time `json:"operated_at_2"`
	Limit        int64     `json:"limit"`
	Offset       int64     `json:"offset"`
}

type GetAdminLogsByTimeRangeRow struct {
	LogID            string                `json:"log_id"`
	OperatorUserID   sql.NullString        `json:"operator_user_id"`
	OperatedAt       time.Time             `json:"operated_at"`
	OperationType    string                `json:"operation_type"`
	Reason           sql.NullString        `json:"reason"`
	Details          pqtype.NullRawMessage `json:"details"`
	IsGlobal         bool                  `json:"is_global"`
	RelatedRoomID    sql.NullString        `json:"related_room_id"`
	RelatedUserID    sql.NullString        `json:"related_user_id"`
	OperatorUsername sql.NullString        `json:"operator_username"`
	OperatorNickname sql.NullString        `json:"operator_nickname"`
	RelatedUsername  sql.NullString        `json:"related_username"`
	RelatedNickname  sql.NullString        `json:"related_nickname"`
}

// 按时间范围获取日志
func (q *Queries) GetAdminLogsByTimeRange(ctx context.Context, arg GetAdminLogsByTimeRangeParams) ([]GetAdminLogsByTimeRangeRow, error) {
	rows, err := q.query(ctx, q.getAdminLogsByTimeRangeStmt, getAdminLogsByTimeRange,
		arg.OperatedAt,
		arg.OperatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminLogsByTimeRangeRow{}
	for rows.Next() {
		var i GetAdminLogsByTimeRangeRow
		if err := rows.Scan(
			&i.LogID,
			&i.OperatorUserID,
			&i.OperatedAt,
			&i.OperationType,
			&i.Reason,
			&i.Details,
			&i.IsGlobal,
			&i.RelatedRoomID,
			&i.RelatedUserID,
			&i.OperatorUsername,
			&i.OperatorNickname,
			&i.RelatedUsername,
			&i.RelatedNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminLogsByType = `-- name: GetAdminLogsByType :many
SELECT 
    al.log_id,
    al.operator_user_id,
    al.operated_at,
    al.operation_type,
    al.reason,
    al.details,
    al.is_global,
    al.related_room_id,
    al.related_user_id,
    ou.username AS operator_username,
    ou.nickname AS operator_nickname,
    ru.username AS related_username,
    ru.nickname AS related_nickname
FROM admin_logs al
LEFT JOIN users ou ON al.operator_user_id = ou.user_id
LEFT JOIN users ru ON al.related_user_id = ru.user_id
WHERE al.operation_type = $1
ORDER BY al.operated_at DESC
LIMIT $2 OFFSET $3
`

type GetAdminLogsByTypeParams struct {
	OperationType string `json:"operation_type"`
	Limit         int64  `json:"limit"`
	Offset        int64  `json:"offset"`
}

type GetAdminLogsByTypeRow struct {
	LogID            string                `json:"log_id"`
	OperatorUserID   sql.NullString        `json:"operator_user_id"`
	OperatedAt       time.Time             `json:"operated_at"`
	OperationType    string                `json:"operation_type"`
	Reason           sql.NullString        `json:"reason"`
	Details          pqtype.NullRawMessage `json:"details"`
	IsGlobal         bool                  `json:"is_global"`
	RelatedRoomID    sql.NullString        `json:"related_room_id"`
	RelatedUserID    sql.NullString        `json:"related_user_id"`
	OperatorUsername sql.NullString        `json:"operator_username"`
	OperatorNickname sql.NullString        `json:"operator_nickname"`
	RelatedUsername  sql.NullString        `json:"related_username"`
	RelatedNickname  sql.NullString        `json:"related_nickname"`
}

// 按操作类型获取日志
func (q *Queries) GetAdminLogsByType(ctx context.Context, arg GetAdminLogsByTypeParams) ([]GetAdminLogsByTypeRow, error) {
	rows, err := q.query(ctx, q.getAdminLogsByTypeStmt, getAdminLogsByType, arg.OperationType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminLogsByTypeRow{}
	for rows.Next() {
		var i GetAdminLogsByTypeRow
		if err := rows.Scan(
			&i.LogID,
			&i.OperatorUserID,
			&i.OperatedAt,
			&i.OperationType,
			&i.Reason,
			&i.Details,
			&i.IsGlobal,
			&i.RelatedRoomID,
			&i.RelatedUserID,
			&i.OperatorUsername,
			&i.OperatorNickname,
			&i.RelatedUsername,
			&i.RelatedNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminLogsByUser = `-- name: GetAdminLogsByUser :many
SELECT 
    al.log_id,
    al.operator_user_id,
    al.operated_at,
    al.operation_type,
    al.reason,
    al.details,
    al.is_global,
    al.related_room_id,
    al.related_user_id,
    ou.username AS operator_username,
    ou.nickname AS operator_nickname
FROM admin_logs al
LEFT JOIN users ou ON al.operator_user_id = ou.user_id
WHERE al.related_user_id = $1
ORDER BY al.operated_at DESC
LIMIT $2 OFFSET $3
`

type GetAdminLogsByUserParams struct {
	RelatedUserID sql.NullString `json:"related_user_id"`
	Limit         int64          `json:"limit"`
	Offset        int64          `json:"offset"`
}

type GetAdminLogsByUserRow struct {
	LogID            string                `json:"log_id"`
	OperatorUserID   sql.NullString        `json:"operator_user_id"`
	OperatedAt       time.Time             `json:"operated_at"`
	OperationType    string                `json:"operation_type"`
	Reason           sql.NullString        `json:"reason"`
	Details          pqtype.NullRawMessage `json:"details"`
	IsGlobal         bool                  `json:"is_global"`
	RelatedRoomID    sql.NullString        `json:"related_room_id"`
	RelatedUserID    sql.NullString        `json:"related_user_id"`
	OperatorUsername sql.NullString        `json:"operator_username"`
	OperatorNickname sql.NullString        `json:"operator_nickname"`
}

// 获取涉及指定用户的日志
func (q *Queries) GetAdminLogsByUser(ctx context.Context, arg GetAdminLogsByUserParams) ([]GetAdminLogsByUserRow, error) {
	rows, err := q.query(ctx, q.getAdminLogsByUserStmt, getAdminLogsByUser, arg.RelatedUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminLogsByUserRow{}
	for rows.Next() {
		var i GetAdminLogsByUserRow
		if err := rows.Scan(
			&i.LogID,
			&i.OperatorUserID,
			&i.OperatedAt,
			&i.OperationType,
			&i.Reason,
			&i.Details,
			&i.IsGlobal,
			&i.RelatedRoomID,
			&i.RelatedUserID,
			&i.OperatorUsername,
			&i.OperatorNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalAdminLogs = `-- name: GetGlobalAdminLogs :many
SELECT 
    al.log_id,
    al.operator_user_id,
    al.operated_at,
    al.operation_type,
    al.reason,
    al.details,
    al.is_global,
    al.related_room_id,
    al.related_user_id,
    ou.username AS operator_username,
    ou.nickname AS operator_nickname,
    ru.username AS related_username,
    ru.nickname AS related_nickname
FROM admin_logs al
LEFT JOIN users ou ON al.operator_user_id = ou.user_id
LEFT JOIN users ru ON al.related_user_id = ru.user_id
WHERE al.is_global = true
ORDER BY al.operated_at DESC
LIMIT $1 OFFSET $2
`

type GetGlobalAdminLogsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type GetGlobalAdminLogsRow struct {
	LogID            string                `json:"log_id"`
	OperatorUserID   sql.NullString        `json:"operator_user_id"`
	OperatedAt       time.Time             `json:"operated_at"`
	OperationType    string                `json:"operation_type"`
	Reason           sql.NullString        `json:"reason"`
	Details          pqtype.NullRawMessage `json:"details"`
	IsGlobal         bool                  `json:"is_global"`
	RelatedRoomID    sql.NullString        `json:"related_room_id"`
	RelatedUserID    sql.NullString        `json:"related_user_id"`
	OperatorUsername sql.NullString        `json:"operator_username"`
	OperatorNickname sql.NullString        `json:"operator_nickname"`
	RelatedUsername  sql.NullString        `json:"related_username"`
	RelatedNickname  sql.NullString        `json:"related_nickname"`
}

// 获取全局管理日志
func (q *Queries) GetGlobalAdminLogs(ctx context.Context, arg GetGlobalAdminLogsParams) ([]GetGlobalAdminLogsRow, error) {
	rows, err := q.query(ctx, q.getGlobalAdminLogsStmt, getGlobalAdminLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGlobalAdminLogsRow{}
	for rows.Next() {
		var i GetGlobalAdminLogsRow
		if err := rows.Scan(
			&i.LogID,
			&i.OperatorUserID,
			&i.OperatedAt,
			&i.OperationType,
			&i.Reason,
			&i.Details,
			&i.IsGlobal,
			&i.RelatedRoomID,
			&i.RelatedUserID,
			&i.OperatorUsername,
			&i.OperatorNickname,
			&i.RelatedUsername,
			&i.RelatedNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOperatorStats = `-- name: GetOperatorStats :many
SELECT 
    al.operator_user_id,
    u.username,
    u.nickname,
    COUNT(*) AS operation_count
FROM admin_logs al
JOIN users u ON al.operator_user_id = u.user_id
GROUP BY al.operator_user_id, u.username, u.nickname
ORDER BY operation_count DESC
LIMIT $1
`

type GetOperatorStatsRow struct {
	OperatorUserID sql.NullString `json:"operator_user_id"`
	Username       string         `json:"username"`
	Nickname       sql.NullString `json:"nickname"`
	OperationCount int64          `json:"operation_count"`
}

// 获取各操作员的操作统计
func (q *Queries) GetOperatorStats(ctx context.Context, limit int64) ([]GetOperatorStatsRow, error) {
	rows, err := q.query(ctx, q.getOperatorStatsStmt, getOperatorStats, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOperatorStatsRow{}
	for rows.Next() {
		var i GetOperatorStatsRow
		if err := rows.Scan(
			&i.OperatorUserID,
			&i.Username,
			&i.Nickname,
			&i.OperationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
