// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chatroom.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const countChatroomMembers = `-- name: CountChatroomMembers :one
SELECT COUNT(*) 
FROM chatroom_members 
WHERE room_id = $1 AND is_active = true
`

func (q *Queries) CountChatroomMembers(ctx context.Context, roomID string) (int64, error) {
	row := q.queryRow(ctx, q.countChatroomMembersStmt, countChatroomMembers, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserChatrooms = `-- name: CountUserChatrooms :one
SELECT COUNT(*) 
FROM chatrooms cr
JOIN chatroom_members cm ON cr.room_id = cm.room_id
WHERE cm.user_id = $1 AND cm.is_active = true AND cr.room_status = 'active'
`

func (q *Queries) CountUserChatrooms(ctx context.Context, userID string) (int64, error) {
	row := q.queryRow(ctx, q.countUserChatroomsStmt, countUserChatrooms, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChatroom = `-- name: CreateChatroom :one
INSERT INTO chatrooms (
    room_name,
    description,
    icon_url,
    room_type,
    access_password
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING 
    room_id,
    room_name,
    description,
    icon_url,
    room_type,
    access_password,
    member_count,
    online_count,
    room_status,
    created_at,
    last_active_at
`

type CreateChatroomParams struct {
	RoomName       string         `json:"room_name"`
	Description    sql.NullString `json:"description"`
	IconUrl        sql.NullString `json:"icon_url"`
	RoomType       ChatroomType   `json:"room_type"`
	AccessPassword sql.NullString `json:"access_password"`
}

func (q *Queries) CreateChatroom(ctx context.Context, arg CreateChatroomParams) (Chatroom, error) {
	row := q.queryRow(ctx, q.createChatroomStmt, createChatroom,
		arg.RoomName,
		arg.Description,
		arg.IconUrl,
		arg.RoomType,
		arg.AccessPassword,
	)
	var i Chatroom
	err := row.Scan(
		&i.RoomID,
		&i.RoomName,
		&i.Description,
		&i.IconUrl,
		&i.RoomType,
		&i.AccessPassword,
		&i.MemberCount,
		&i.OnlineCount,
		&i.RoomStatus,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const decrementChatroomMemberCount = `-- name: DecrementChatroomMemberCount :exec
UPDATE chatrooms 
SET member_count = member_count - 1
WHERE room_id = $1
`

func (q *Queries) DecrementChatroomMemberCount(ctx context.Context, roomID string) error {
	_, err := q.exec(ctx, q.decrementChatroomMemberCountStmt, decrementChatroomMemberCount, roomID)
	return err
}

const decrementChatroomOnlineCount = `-- name: DecrementChatroomOnlineCount :exec
UPDATE chatrooms 
SET online_count = online_count - 1
WHERE room_id = $1
`

func (q *Queries) DecrementChatroomOnlineCount(ctx context.Context, roomID string) error {
	_, err := q.exec(ctx, q.decrementChatroomOnlineCountStmt, decrementChatroomOnlineCount, roomID)
	return err
}

const deleteChatroom = `-- name: DeleteChatroom :exec
UPDATE chatrooms 
SET room_status = 'deleted'
WHERE room_id = $1
`

func (q *Queries) DeleteChatroom(ctx context.Context, roomID string) error {
	_, err := q.exec(ctx, q.deleteChatroomStmt, deleteChatroom, roomID)
	return err
}

const getChatroomByID = `-- name: GetChatroomByID :one
SELECT 
    room_id,
    room_name,
    description,
    icon_url,
    room_type,
    access_password,
    member_count,
    online_count,
    room_status,
    created_at,
    last_active_at
FROM chatrooms 
WHERE room_id = $1 AND room_status = 'active'
`

func (q *Queries) GetChatroomByID(ctx context.Context, roomID string) (Chatroom, error) {
	row := q.queryRow(ctx, q.getChatroomByIDStmt, getChatroomByID, roomID)
	var i Chatroom
	err := row.Scan(
		&i.RoomID,
		&i.RoomName,
		&i.Description,
		&i.IconUrl,
		&i.RoomType,
		&i.AccessPassword,
		&i.MemberCount,
		&i.OnlineCount,
		&i.RoomStatus,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const getChatroomMembers = `-- name: GetChatroomMembers :many
SELECT 
    u.user_id,
    u.username,
    u.nickname,
    u.avatar_url,
    u.online_status,
    cm.member_rel_id,
    cm.joined_at,
    cm.member_role,
    cm.mute_status,
    cm.mute_expires_at,
    cm.is_active
FROM chatroom_members cm
JOIN users u ON cm.user_id = u.user_id
WHERE cm.room_id = $1 AND cm.is_active = true
ORDER BY cm.joined_at ASC
LIMIT $2 OFFSET $3
`

type GetChatroomMembersParams struct {
	RoomID string `json:"room_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type GetChatroomMembersRow struct {
	UserID        string               `json:"user_id"`
	Username      string               `json:"username"`
	Nickname      sql.NullString       `json:"nickname"`
	AvatarUrl     sql.NullString       `json:"avatar_url"`
	OnlineStatus  NullUserOnlineStatus `json:"online_status"`
	MemberRelID   string               `json:"member_rel_id"`
	JoinedAt      time.Time            `json:"joined_at"`
	MemberRole    MemberRole           `json:"member_role"`
	MuteStatus    MemberMuteStatus     `json:"mute_status"`
	MuteExpiresAt sql.NullTime         `json:"mute_expires_at"`
	IsActive      bool                 `json:"is_active"`
}

func (q *Queries) GetChatroomMembers(ctx context.Context, arg GetChatroomMembersParams) ([]GetChatroomMembersRow, error) {
	rows, err := q.query(ctx, q.getChatroomMembersStmt, getChatroomMembers, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatroomMembersRow{}
	for rows.Next() {
		var i GetChatroomMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Nickname,
			&i.AvatarUrl,
			&i.OnlineStatus,
			&i.MemberRelID,
			&i.JoinedAt,
			&i.MemberRole,
			&i.MuteStatus,
			&i.MuteExpiresAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserChatroomMembership = `-- name: GetUserChatroomMembership :one
SELECT 
    member_rel_id,
    user_id,
    room_id,
    joined_at,
    left_at,
    last_read_at,
    member_role,
    mute_status,
    mute_expires_at,
    is_active
FROM chatroom_members 
WHERE user_id = $1 AND room_id = $2
`

type GetUserChatroomMembershipParams struct {
	UserID string `json:"user_id"`
	RoomID string `json:"room_id"`
}

func (q *Queries) GetUserChatroomMembership(ctx context.Context, arg GetUserChatroomMembershipParams) (ChatroomMember, error) {
	row := q.queryRow(ctx, q.getUserChatroomMembershipStmt, getUserChatroomMembership, arg.UserID, arg.RoomID)
	var i ChatroomMember
	err := row.Scan(
		&i.MemberRelID,
		&i.UserID,
		&i.RoomID,
		&i.JoinedAt,
		&i.LeftAt,
		&i.LastReadAt,
		&i.MemberRole,
		&i.MuteStatus,
		&i.MuteExpiresAt,
		&i.IsActive,
	)
	return i, err
}

const incrementChatroomMemberCount = `-- name: IncrementChatroomMemberCount :exec
UPDATE chatrooms 
SET member_count = member_count + 1
WHERE room_id = $1
`

func (q *Queries) IncrementChatroomMemberCount(ctx context.Context, roomID string) error {
	_, err := q.exec(ctx, q.incrementChatroomMemberCountStmt, incrementChatroomMemberCount, roomID)
	return err
}

const incrementChatroomOnlineCount = `-- name: IncrementChatroomOnlineCount :exec
UPDATE chatrooms 
SET online_count = online_count + 1
WHERE room_id = $1
`

func (q *Queries) IncrementChatroomOnlineCount(ctx context.Context, roomID string) error {
	_, err := q.exec(ctx, q.incrementChatroomOnlineCountStmt, incrementChatroomOnlineCount, roomID)
	return err
}

const isMemberMuted = `-- name: IsMemberMuted :one
SELECT 
    CASE 
        WHEN mute_status = 'muted' AND (mute_expires_at IS NULL OR mute_expires_at > NOW()) 
        THEN true 
        ELSE false 
    END as is_muted
FROM chatroom_members 
WHERE user_id = $1 AND room_id = $2 AND is_active = true
`

type IsMemberMutedParams struct {
	UserID string `json:"user_id"`
	RoomID string `json:"room_id"`
}

func (q *Queries) IsMemberMuted(ctx context.Context, arg IsMemberMutedParams) (bool, error) {
	row := q.queryRow(ctx, q.isMemberMutedStmt, isMemberMuted, arg.UserID, arg.RoomID)
	var is_muted bool
	err := row.Scan(&is_muted)
	return is_muted, err
}

const joinChatroom = `-- name: JoinChatroom :one
INSERT INTO chatroom_members (
    user_id,
    room_id,
    member_role
) VALUES (
    $1, $2, 'member'
) 
ON CONFLICT (user_id, room_id) 
DO UPDATE SET 
    is_active = true,
    joined_at = NOW(),
    left_at = NULL
RETURNING 
    member_rel_id,
    user_id,
    room_id,
    joined_at,
    left_at,
    last_read_at,
    member_role,
    mute_status,
    mute_expires_at,
    is_active
`

type JoinChatroomParams struct {
	UserID string `json:"user_id"`
	RoomID string `json:"room_id"`
}

func (q *Queries) JoinChatroom(ctx context.Context, arg JoinChatroomParams) (ChatroomMember, error) {
	row := q.queryRow(ctx, q.joinChatroomStmt, joinChatroom, arg.UserID, arg.RoomID)
	var i ChatroomMember
	err := row.Scan(
		&i.MemberRelID,
		&i.UserID,
		&i.RoomID,
		&i.JoinedAt,
		&i.LeftAt,
		&i.LastReadAt,
		&i.MemberRole,
		&i.MuteStatus,
		&i.MuteExpiresAt,
		&i.IsActive,
	)
	return i, err
}

const leaveChatroom = `-- name: LeaveChatroom :exec
UPDATE chatroom_members 
SET 
    is_active = false,
    left_at = NOW()
WHERE user_id = $1 AND room_id = $2
`

type LeaveChatroomParams struct {
	UserID string `json:"user_id"`
	RoomID string `json:"room_id"`
}

func (q *Queries) LeaveChatroom(ctx context.Context, arg LeaveChatroomParams) error {
	_, err := q.exec(ctx, q.leaveChatroomStmt, leaveChatroom, arg.UserID, arg.RoomID)
	return err
}

const listUserChatrooms = `-- name: ListUserChatrooms :many
SELECT 
    cr.room_id,
    cr.room_name,
    cr.description,
    cr.icon_url,
    cr.room_type,
    cr.access_password,
    cr.member_count,
    cr.online_count,
    cr.room_status,
    cr.created_at,
    cr.last_active_at,
    cm.member_rel_id,
    cm.joined_at,
    cm.member_role,
    cm.mute_status,
    cm.is_active
FROM chatrooms cr
JOIN chatroom_members cm ON cr.room_id = cm.room_id
WHERE cm.user_id = $1 AND cm.is_active = true AND cr.room_status = 'active'
ORDER BY cr.last_active_at DESC
LIMIT $2 OFFSET $3
`

type ListUserChatroomsParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type ListUserChatroomsRow struct {
	RoomID         string           `json:"room_id"`
	RoomName       string           `json:"room_name"`
	Description    sql.NullString   `json:"description"`
	IconUrl        sql.NullString   `json:"icon_url"`
	RoomType       ChatroomType     `json:"room_type"`
	AccessPassword sql.NullString   `json:"access_password"`
	MemberCount    int32            `json:"member_count"`
	OnlineCount    int32            `json:"online_count"`
	RoomStatus     ChatroomStatus   `json:"room_status"`
	CreatedAt      time.Time        `json:"created_at"`
	LastActiveAt   sql.NullTime     `json:"last_active_at"`
	MemberRelID    string           `json:"member_rel_id"`
	JoinedAt       time.Time        `json:"joined_at"`
	MemberRole     MemberRole       `json:"member_role"`
	MuteStatus     MemberMuteStatus `json:"mute_status"`
	IsActive       bool             `json:"is_active"`
}

func (q *Queries) ListUserChatrooms(ctx context.Context, arg ListUserChatroomsParams) ([]ListUserChatroomsRow, error) {
	rows, err := q.query(ctx, q.listUserChatroomsStmt, listUserChatrooms, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserChatroomsRow{}
	for rows.Next() {
		var i ListUserChatroomsRow
		if err := rows.Scan(
			&i.RoomID,
			&i.RoomName,
			&i.Description,
			&i.IconUrl,
			&i.RoomType,
			&i.AccessPassword,
			&i.MemberCount,
			&i.OnlineCount,
			&i.RoomStatus,
			&i.CreatedAt,
			&i.LastActiveAt,
			&i.MemberRelID,
			&i.JoinedAt,
			&i.MemberRole,
			&i.MuteStatus,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const muteMember = `-- name: MuteMember :exec
UPDATE chatroom_members 
SET 
    mute_status = 'muted',
    mute_expires_at = $3
WHERE user_id = $1 AND room_id = $2
`

type MuteMemberParams struct {
	UserID        string       `json:"user_id"`
	RoomID        string       `json:"room_id"`
	MuteExpiresAt sql.NullTime `json:"mute_expires_at"`
}

func (q *Queries) MuteMember(ctx context.Context, arg MuteMemberParams) error {
	_, err := q.exec(ctx, q.muteMemberStmt, muteMember, arg.UserID, arg.RoomID, arg.MuteExpiresAt)
	return err
}

const setMemberRole = `-- name: SetMemberRole :exec
UPDATE chatroom_members 
SET member_role = $3
WHERE user_id = $1 AND room_id = $2
`

type SetMemberRoleParams struct {
	UserID     string     `json:"user_id"`
	RoomID     string     `json:"room_id"`
	MemberRole MemberRole `json:"member_role"`
}

func (q *Queries) SetMemberRole(ctx context.Context, arg SetMemberRoleParams) error {
	_, err := q.exec(ctx, q.setMemberRoleStmt, setMemberRole, arg.UserID, arg.RoomID, arg.MemberRole)
	return err
}

const unmuteMember = `-- name: UnmuteMember :exec
UPDATE chatroom_members 
SET 
    mute_status = 'not_muted',
    mute_expires_at = NULL
WHERE user_id = $1 AND room_id = $2
`

type UnmuteMemberParams struct {
	UserID string `json:"user_id"`
	RoomID string `json:"room_id"`
}

func (q *Queries) UnmuteMember(ctx context.Context, arg UnmuteMemberParams) error {
	_, err := q.exec(ctx, q.unmuteMemberStmt, unmuteMember, arg.UserID, arg.RoomID)
	return err
}

const updateChatroom = `-- name: UpdateChatroom :one
UPDATE chatrooms 
SET 
    room_name = $2,
    description = $3,
    icon_url = $4,
    room_type = $5,
    access_password = $6,
    last_active_at = NOW()
WHERE room_id = $1
RETURNING 
    room_id,
    room_name,
    description,
    icon_url,
    room_type,
    access_password,
    member_count,
    online_count,
    room_status,
    created_at,
    last_active_at
`

type UpdateChatroomParams struct {
	RoomID         string         `json:"room_id"`
	RoomName       string         `json:"room_name"`
	Description    sql.NullString `json:"description"`
	IconUrl        sql.NullString `json:"icon_url"`
	RoomType       ChatroomType   `json:"room_type"`
	AccessPassword sql.NullString `json:"access_password"`
}

func (q *Queries) UpdateChatroom(ctx context.Context, arg UpdateChatroomParams) (Chatroom, error) {
	row := q.queryRow(ctx, q.updateChatroomStmt, updateChatroom,
		arg.RoomID,
		arg.RoomName,
		arg.Description,
		arg.IconUrl,
		arg.RoomType,
		arg.AccessPassword,
	)
	var i Chatroom
	err := row.Scan(
		&i.RoomID,
		&i.RoomName,
		&i.Description,
		&i.IconUrl,
		&i.RoomType,
		&i.AccessPassword,
		&i.MemberCount,
		&i.OnlineCount,
		&i.RoomStatus,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const updateChatroomLastActiveTime = `-- name: UpdateChatroomLastActiveTime :exec
UPDATE chatrooms 
SET last_active_at = NOW()
WHERE room_id = $1
`

func (q *Queries) UpdateChatroomLastActiveTime(ctx context.Context, roomID string) error {
	_, err := q.exec(ctx, q.updateChatroomLastActiveTimeStmt, updateChatroomLastActiveTime, roomID)
	return err
}

const updateMemberLastReadTime = `-- name: UpdateMemberLastReadTime :exec
UPDATE chatroom_members 
SET last_read_at = NOW()
WHERE user_id = $1 AND room_id = $2
`

type UpdateMemberLastReadTimeParams struct {
	UserID string `json:"user_id"`
	RoomID string `json:"room_id"`
}

func (q *Queries) UpdateMemberLastReadTime(ctx context.Context, arg UpdateMemberLastReadTimeParams) error {
	_, err := q.exec(ctx, q.updateMemberLastReadTimeStmt, updateMemberLastReadTime, arg.UserID, arg.RoomID)
	return err
}
