// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countChatroomMembersStmt, err = db.PrepareContext(ctx, countChatroomMembers); err != nil {
		return nil, fmt.Errorf("error preparing query CountChatroomMembers: %w", err)
	}
	if q.countUserChatroomsStmt, err = db.PrepareContext(ctx, countUserChatrooms); err != nil {
		return nil, fmt.Errorf("error preparing query CountUserChatrooms: %w", err)
	}
	if q.createChatroomStmt, err = db.PrepareContext(ctx, createChatroom); err != nil {
		return nil, fmt.Errorf("error preparing query CreateChatroom: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.decrementChatroomMemberCountStmt, err = db.PrepareContext(ctx, decrementChatroomMemberCount); err != nil {
		return nil, fmt.Errorf("error preparing query DecrementChatroomMemberCount: %w", err)
	}
	if q.decrementChatroomOnlineCountStmt, err = db.PrepareContext(ctx, decrementChatroomOnlineCount); err != nil {
		return nil, fmt.Errorf("error preparing query DecrementChatroomOnlineCount: %w", err)
	}
	if q.deleteChatroomStmt, err = db.PrepareContext(ctx, deleteChatroom); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteChatroom: %w", err)
	}
	if q.deleteMessageStmt, err = db.PrepareContext(ctx, deleteMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessage: %w", err)
	}
	if q.getChatroomByIDStmt, err = db.PrepareContext(ctx, getChatroomByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetChatroomByID: %w", err)
	}
	if q.getChatroomMembersStmt, err = db.PrepareContext(ctx, getChatroomMembers); err != nil {
		return nil, fmt.Errorf("error preparing query GetChatroomMembers: %w", err)
	}
	if q.getMessageByIDStmt, err = db.PrepareContext(ctx, getMessageByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessageByID: %w", err)
	}
	if q.getMessagesByRoomStmt, err = db.PrepareContext(ctx, getMessagesByRoom); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessagesByRoom: %w", err)
	}
	if q.getUnreadMessageCountStmt, err = db.PrepareContext(ctx, getUnreadMessageCount); err != nil {
		return nil, fmt.Errorf("error preparing query GetUnreadMessageCount: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserByUsernameStmt, err = db.PrepareContext(ctx, getUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsername: %w", err)
	}
	if q.getUserChatroomMembershipStmt, err = db.PrepareContext(ctx, getUserChatroomMembership); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserChatroomMembership: %w", err)
	}
	if q.incrementChatroomMemberCountStmt, err = db.PrepareContext(ctx, incrementChatroomMemberCount); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementChatroomMemberCount: %w", err)
	}
	if q.incrementChatroomOnlineCountStmt, err = db.PrepareContext(ctx, incrementChatroomOnlineCount); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementChatroomOnlineCount: %w", err)
	}
	if q.isMemberMutedStmt, err = db.PrepareContext(ctx, isMemberMuted); err != nil {
		return nil, fmt.Errorf("error preparing query IsMemberMuted: %w", err)
	}
	if q.joinChatroomStmt, err = db.PrepareContext(ctx, joinChatroom); err != nil {
		return nil, fmt.Errorf("error preparing query JoinChatroom: %w", err)
	}
	if q.leaveChatroomStmt, err = db.PrepareContext(ctx, leaveChatroom); err != nil {
		return nil, fmt.Errorf("error preparing query LeaveChatroom: %w", err)
	}
	if q.listUserChatroomsStmt, err = db.PrepareContext(ctx, listUserChatrooms); err != nil {
		return nil, fmt.Errorf("error preparing query ListUserChatrooms: %w", err)
	}
	if q.muteMemberStmt, err = db.PrepareContext(ctx, muteMember); err != nil {
		return nil, fmt.Errorf("error preparing query MuteMember: %w", err)
	}
	if q.setMemberRoleStmt, err = db.PrepareContext(ctx, setMemberRole); err != nil {
		return nil, fmt.Errorf("error preparing query SetMemberRole: %w", err)
	}
	if q.unmuteMemberStmt, err = db.PrepareContext(ctx, unmuteMember); err != nil {
		return nil, fmt.Errorf("error preparing query UnmuteMember: %w", err)
	}
	if q.updateChatroomStmt, err = db.PrepareContext(ctx, updateChatroom); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateChatroom: %w", err)
	}
	if q.updateChatroomLastActiveTimeStmt, err = db.PrepareContext(ctx, updateChatroomLastActiveTime); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateChatroomLastActiveTime: %w", err)
	}
	if q.updateMemberLastReadTimeStmt, err = db.PrepareContext(ctx, updateMemberLastReadTime); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMemberLastReadTime: %w", err)
	}
	if q.updateMessageStmt, err = db.PrepareContext(ctx, updateMessage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessage: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	if q.updateUserPasswordStmt, err = db.PrepareContext(ctx, updateUserPassword); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserPassword: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countChatroomMembersStmt != nil {
		if cerr := q.countChatroomMembersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countChatroomMembersStmt: %w", cerr)
		}
	}
	if q.countUserChatroomsStmt != nil {
		if cerr := q.countUserChatroomsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countUserChatroomsStmt: %w", cerr)
		}
	}
	if q.createChatroomStmt != nil {
		if cerr := q.createChatroomStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createChatroomStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.decrementChatroomMemberCountStmt != nil {
		if cerr := q.decrementChatroomMemberCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing decrementChatroomMemberCountStmt: %w", cerr)
		}
	}
	if q.decrementChatroomOnlineCountStmt != nil {
		if cerr := q.decrementChatroomOnlineCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing decrementChatroomOnlineCountStmt: %w", cerr)
		}
	}
	if q.deleteChatroomStmt != nil {
		if cerr := q.deleteChatroomStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteChatroomStmt: %w", cerr)
		}
	}
	if q.deleteMessageStmt != nil {
		if cerr := q.deleteMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageStmt: %w", cerr)
		}
	}
	if q.getChatroomByIDStmt != nil {
		if cerr := q.getChatroomByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChatroomByIDStmt: %w", cerr)
		}
	}
	if q.getChatroomMembersStmt != nil {
		if cerr := q.getChatroomMembersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getChatroomMembersStmt: %w", cerr)
		}
	}
	if q.getMessageByIDStmt != nil {
		if cerr := q.getMessageByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageByIDStmt: %w", cerr)
		}
	}
	if q.getMessagesByRoomStmt != nil {
		if cerr := q.getMessagesByRoomStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessagesByRoomStmt: %w", cerr)
		}
	}
	if q.getUnreadMessageCountStmt != nil {
		if cerr := q.getUnreadMessageCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUnreadMessageCountStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameStmt != nil {
		if cerr := q.getUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameStmt: %w", cerr)
		}
	}
	if q.getUserChatroomMembershipStmt != nil {
		if cerr := q.getUserChatroomMembershipStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserChatroomMembershipStmt: %w", cerr)
		}
	}
	if q.incrementChatroomMemberCountStmt != nil {
		if cerr := q.incrementChatroomMemberCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementChatroomMemberCountStmt: %w", cerr)
		}
	}
	if q.incrementChatroomOnlineCountStmt != nil {
		if cerr := q.incrementChatroomOnlineCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementChatroomOnlineCountStmt: %w", cerr)
		}
	}
	if q.isMemberMutedStmt != nil {
		if cerr := q.isMemberMutedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isMemberMutedStmt: %w", cerr)
		}
	}
	if q.joinChatroomStmt != nil {
		if cerr := q.joinChatroomStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing joinChatroomStmt: %w", cerr)
		}
	}
	if q.leaveChatroomStmt != nil {
		if cerr := q.leaveChatroomStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing leaveChatroomStmt: %w", cerr)
		}
	}
	if q.listUserChatroomsStmt != nil {
		if cerr := q.listUserChatroomsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUserChatroomsStmt: %w", cerr)
		}
	}
	if q.muteMemberStmt != nil {
		if cerr := q.muteMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing muteMemberStmt: %w", cerr)
		}
	}
	if q.setMemberRoleStmt != nil {
		if cerr := q.setMemberRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setMemberRoleStmt: %w", cerr)
		}
	}
	if q.unmuteMemberStmt != nil {
		if cerr := q.unmuteMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing unmuteMemberStmt: %w", cerr)
		}
	}
	if q.updateChatroomStmt != nil {
		if cerr := q.updateChatroomStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateChatroomStmt: %w", cerr)
		}
	}
	if q.updateChatroomLastActiveTimeStmt != nil {
		if cerr := q.updateChatroomLastActiveTimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateChatroomLastActiveTimeStmt: %w", cerr)
		}
	}
	if q.updateMemberLastReadTimeStmt != nil {
		if cerr := q.updateMemberLastReadTimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMemberLastReadTimeStmt: %w", cerr)
		}
	}
	if q.updateMessageStmt != nil {
		if cerr := q.updateMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	if q.updateUserPasswordStmt != nil {
		if cerr := q.updateUserPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserPasswordStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	countChatroomMembersStmt         *sql.Stmt
	countUserChatroomsStmt           *sql.Stmt
	createChatroomStmt               *sql.Stmt
	createMessageStmt                *sql.Stmt
	createUserStmt                   *sql.Stmt
	decrementChatroomMemberCountStmt *sql.Stmt
	decrementChatroomOnlineCountStmt *sql.Stmt
	deleteChatroomStmt               *sql.Stmt
	deleteMessageStmt                *sql.Stmt
	getChatroomByIDStmt              *sql.Stmt
	getChatroomMembersStmt           *sql.Stmt
	getMessageByIDStmt               *sql.Stmt
	getMessagesByRoomStmt            *sql.Stmt
	getUnreadMessageCountStmt        *sql.Stmt
	getUserByIDStmt                  *sql.Stmt
	getUserByUsernameStmt            *sql.Stmt
	getUserChatroomMembershipStmt    *sql.Stmt
	incrementChatroomMemberCountStmt *sql.Stmt
	incrementChatroomOnlineCountStmt *sql.Stmt
	isMemberMutedStmt                *sql.Stmt
	joinChatroomStmt                 *sql.Stmt
	leaveChatroomStmt                *sql.Stmt
	listUserChatroomsStmt            *sql.Stmt
	muteMemberStmt                   *sql.Stmt
	setMemberRoleStmt                *sql.Stmt
	unmuteMemberStmt                 *sql.Stmt
	updateChatroomStmt               *sql.Stmt
	updateChatroomLastActiveTimeStmt *sql.Stmt
	updateMemberLastReadTimeStmt     *sql.Stmt
	updateMessageStmt                *sql.Stmt
	updateUserStmt                   *sql.Stmt
	updateUserPasswordStmt           *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		countChatroomMembersStmt:         q.countChatroomMembersStmt,
		countUserChatroomsStmt:           q.countUserChatroomsStmt,
		createChatroomStmt:               q.createChatroomStmt,
		createMessageStmt:                q.createMessageStmt,
		createUserStmt:                   q.createUserStmt,
		decrementChatroomMemberCountStmt: q.decrementChatroomMemberCountStmt,
		decrementChatroomOnlineCountStmt: q.decrementChatroomOnlineCountStmt,
		deleteChatroomStmt:               q.deleteChatroomStmt,
		deleteMessageStmt:                q.deleteMessageStmt,
		getChatroomByIDStmt:              q.getChatroomByIDStmt,
		getChatroomMembersStmt:           q.getChatroomMembersStmt,
		getMessageByIDStmt:               q.getMessageByIDStmt,
		getMessagesByRoomStmt:            q.getMessagesByRoomStmt,
		getUnreadMessageCountStmt:        q.getUnreadMessageCountStmt,
		getUserByIDStmt:                  q.getUserByIDStmt,
		getUserByUsernameStmt:            q.getUserByUsernameStmt,
		getUserChatroomMembershipStmt:    q.getUserChatroomMembershipStmt,
		incrementChatroomMemberCountStmt: q.incrementChatroomMemberCountStmt,
		incrementChatroomOnlineCountStmt: q.incrementChatroomOnlineCountStmt,
		isMemberMutedStmt:                q.isMemberMutedStmt,
		joinChatroomStmt:                 q.joinChatroomStmt,
		leaveChatroomStmt:                q.leaveChatroomStmt,
		listUserChatroomsStmt:            q.listUserChatroomsStmt,
		muteMemberStmt:                   q.muteMemberStmt,
		setMemberRoleStmt:                q.setMemberRoleStmt,
		unmuteMemberStmt:                 q.unmuteMemberStmt,
		updateChatroomStmt:               q.updateChatroomStmt,
		updateChatroomLastActiveTimeStmt: q.updateChatroomLastActiveTimeStmt,
		updateMemberLastReadTimeStmt:     q.updateMemberLastReadTimeStmt,
		updateMessageStmt:                q.updateMessageStmt,
		updateUserStmt:                   q.updateUserStmt,
		updateUserPasswordStmt:           q.updateUserPasswordStmt,
	}
}
