// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    content,
    message_type,
    quoted_message_id,
    sender_id,
    room_id
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING 
    message_id,
    sent_at,
    content,
    message_type,
    quoted_message_id,
    sender_id,
    room_id
`

type CreateMessageParams struct {
	Content         string         `json:"content"`
	MessageType     MessageType    `json:"message_type"`
	QuotedMessageID sql.NullString `json:"quoted_message_id"`
	SenderID        sql.NullString `json:"sender_id"`
	RoomID          string         `json:"room_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.queryRow(ctx, q.createMessageStmt, createMessage,
		arg.Content,
		arg.MessageType,
		arg.QuotedMessageID,
		arg.SenderID,
		arg.RoomID,
	)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.SentAt,
		&i.Content,
		&i.MessageType,
		&i.QuotedMessageID,
		&i.SenderID,
		&i.RoomID,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages 
WHERE message_id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, messageID string) error {
	_, err := q.exec(ctx, q.deleteMessageStmt, deleteMessage, messageID)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT 
    message_id,
    sent_at,
    content,
    message_type,
    quoted_message_id,
    sender_id,
    room_id
FROM messages 
WHERE message_id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, messageID string) (Message, error) {
	row := q.queryRow(ctx, q.getMessageByIDStmt, getMessageByID, messageID)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.SentAt,
		&i.Content,
		&i.MessageType,
		&i.QuotedMessageID,
		&i.SenderID,
		&i.RoomID,
	)
	return i, err
}

const getMessagesByRoom = `-- name: GetMessagesByRoom :many
SELECT 
    message_id,
    sent_at,
    content,
    message_type,
    quoted_message_id,
    sender_id,
    room_id
FROM messages 
WHERE room_id = $1
ORDER BY sent_at DESC
LIMIT $2 OFFSET $3
`

type GetMessagesByRoomParams struct {
	RoomID string `json:"room_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) GetMessagesByRoom(ctx context.Context, arg GetMessagesByRoomParams) ([]Message, error) {
	rows, err := q.query(ctx, q.getMessagesByRoomStmt, getMessagesByRoom, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.MessageID,
			&i.SentAt,
			&i.Content,
			&i.MessageType,
			&i.QuotedMessageID,
			&i.SenderID,
			&i.RoomID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadMessageCount = `-- name: GetUnreadMessageCount :one
SELECT COUNT(*) 
FROM messages m
LEFT JOIN chatroom_members cm ON m.room_id = cm.room_id AND cm.user_id = $1
WHERE m.room_id = $2 
    AND m.sent_at > COALESCE(cm.last_read_at, '1970-01-01'::TIMESTAMPTZ)
`

type GetUnreadMessageCountParams struct {
	UserID string `json:"user_id"`
	RoomID string `json:"room_id"`
}

func (q *Queries) GetUnreadMessageCount(ctx context.Context, arg GetUnreadMessageCountParams) (int64, error) {
	row := q.queryRow(ctx, q.getUnreadMessageCountStmt, getUnreadMessageCount, arg.UserID, arg.RoomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages 
SET 
    content = $2,
    sent_at = NOW()
WHERE message_id = $1
RETURNING 
    message_id,
    sent_at,
    content,
    message_type,
    quoted_message_id,
    sender_id,
    room_id
`

type UpdateMessageParams struct {
	MessageID string `json:"message_id"`
	Content   string `json:"content"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error) {
	row := q.queryRow(ctx, q.updateMessageStmt, updateMessage, arg.MessageID, arg.Content)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.SentAt,
		&i.Content,
		&i.MessageType,
		&i.QuotedMessageID,
		&i.SenderID,
		&i.RoomID,
	)
	return i, err
}
