// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type ChatroomStatus string

const (
	ChatroomStatusActive   ChatroomStatus = "active"
	ChatroomStatusArchived ChatroomStatus = "archived"
	ChatroomStatusDeleted  ChatroomStatus = "deleted"
)

func (e *ChatroomStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatroomStatus(s)
	case string:
		*e = ChatroomStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatroomStatus: %T", src)
	}
	return nil
}

type NullChatroomStatus struct {
	ChatroomStatus ChatroomStatus `json:"chatroom_status"`
	Valid          bool           `json:"valid"` // Valid is true if ChatroomStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatroomStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ChatroomStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatroomStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatroomStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatroomStatus), nil
}

type ChatroomType string

const (
	ChatroomTypePublic            ChatroomType = "public"
	ChatroomTypePrivatePassword   ChatroomType = "private_password"
	ChatroomTypePrivateInviteOnly ChatroomType = "private_invite_only"
)

func (e *ChatroomType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatroomType(s)
	case string:
		*e = ChatroomType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatroomType: %T", src)
	}
	return nil
}

type NullChatroomType struct {
	ChatroomType ChatroomType `json:"chatroom_type"`
	Valid        bool         `json:"valid"` // Valid is true if ChatroomType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatroomType) Scan(value interface{}) error {
	if value == nil {
		ns.ChatroomType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatroomType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatroomType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatroomType), nil
}

type MemberMuteStatus string

const (
	MemberMuteStatusNotMuted MemberMuteStatus = "not_muted"
	MemberMuteStatusMuted    MemberMuteStatus = "muted"
)

func (e *MemberMuteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberMuteStatus(s)
	case string:
		*e = MemberMuteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberMuteStatus: %T", src)
	}
	return nil
}

type NullMemberMuteStatus struct {
	MemberMuteStatus MemberMuteStatus `json:"member_mute_status"`
	Valid            bool             `json:"valid"` // Valid is true if MemberMuteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberMuteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MemberMuteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberMuteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberMuteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberMuteStatus), nil
}

type MemberRole string

const (
	MemberRoleOwner  MemberRole = "owner"
	MemberRoleAdmin  MemberRole = "admin"
	MemberRoleMember MemberRole = "member"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole `json:"member_role"`
	Valid      bool       `json:"valid"` // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type MessageStatus string

const (
	MessageStatusSent      MessageStatus = "sent"
	MessageStatusDelivered MessageStatus = "delivered"
	MessageStatusRead      MessageStatus = "read"
	MessageStatusFailed    MessageStatus = "failed"
	MessageStatusDeleted   MessageStatus = "deleted"
)

func (e *MessageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageStatus(s)
	case string:
		*e = MessageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageStatus: %T", src)
	}
	return nil
}

type NullMessageStatus struct {
	MessageStatus MessageStatus `json:"message_status"`
	Valid         bool          `json:"valid"` // Valid is true if MessageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MessageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageStatus), nil
}

type MessageType string

const (
	MessageTypeText               MessageType = "text"
	MessageTypeImage              MessageType = "image"
	MessageTypeFile               MessageType = "file"
	MessageTypeSystemNotification MessageType = "system_notification"
)

func (e *MessageType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageType(s)
	case string:
		*e = MessageType(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageType: %T", src)
	}
	return nil
}

type NullMessageType struct {
	MessageType MessageType `json:"message_type"`
	Valid       bool        `json:"valid"` // Valid is true if MessageType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageType) Scan(value interface{}) error {
	if value == nil {
		ns.MessageType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageType), nil
}

type UserAccountStatus string

const (
	UserAccountStatusActive              UserAccountStatus = "active"
	UserAccountStatusSuspended           UserAccountStatus = "suspended"
	UserAccountStatusDeleted             UserAccountStatus = "deleted"
	UserAccountStatusPendingVerification UserAccountStatus = "pending_verification"
)

func (e *UserAccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserAccountStatus(s)
	case string:
		*e = UserAccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserAccountStatus: %T", src)
	}
	return nil
}

type NullUserAccountStatus struct {
	UserAccountStatus UserAccountStatus `json:"user_account_status"`
	Valid             bool              `json:"valid"` // Valid is true if UserAccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserAccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserAccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserAccountStatus), nil
}

type UserOnlineStatus string

const (
	UserOnlineStatusOnline       UserOnlineStatus = "online"
	UserOnlineStatusOffline      UserOnlineStatus = "offline"
	UserOnlineStatusAway         UserOnlineStatus = "away"
	UserOnlineStatusDoNotDisturb UserOnlineStatus = "do_not_disturb"
)

func (e *UserOnlineStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserOnlineStatus(s)
	case string:
		*e = UserOnlineStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserOnlineStatus: %T", src)
	}
	return nil
}

type NullUserOnlineStatus struct {
	UserOnlineStatus UserOnlineStatus `json:"user_online_status"`
	Valid            bool             `json:"valid"` // Valid is true if UserOnlineStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserOnlineStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserOnlineStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserOnlineStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserOnlineStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserOnlineStatus), nil
}

type UserSystemRole string

const (
	UserSystemRoleAdmin UserSystemRole = "admin"
	UserSystemRoleUser  UserSystemRole = "user"
)

func (e *UserSystemRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserSystemRole(s)
	case string:
		*e = UserSystemRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserSystemRole: %T", src)
	}
	return nil
}

type NullUserSystemRole struct {
	UserSystemRole UserSystemRole `json:"user_system_role"`
	Valid          bool           `json:"valid"` // Valid is true if UserSystemRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserSystemRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserSystemRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserSystemRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserSystemRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserSystemRole), nil
}

type AdminLog struct {
	LogID          string                `json:"log_id"`
	OperatorUserID sql.NullString        `json:"operator_user_id"`
	OperatedAt     time.Time             `json:"operated_at"`
	OperationType  string                `json:"operation_type"`
	Reason         sql.NullString        `json:"reason"`
	Details        pqtype.NullRawMessage `json:"details"`
	IsGlobal       bool                  `json:"is_global"`
	RelatedRoomID  sql.NullString        `json:"related_room_id"`
	RelatedUserID  sql.NullString        `json:"related_user_id"`
}

type Chatroom struct {
	RoomID         string         `json:"room_id"`
	RoomName       string         `json:"room_name"`
	Description    sql.NullString `json:"description"`
	IconUrl        sql.NullString `json:"icon_url"`
	RoomType       ChatroomType   `json:"room_type"`
	AccessPassword sql.NullString `json:"access_password"`
	MemberCount    int32          `json:"member_count"`
	OnlineCount    int32          `json:"online_count"`
	RoomStatus     ChatroomStatus `json:"room_status"`
	CreatedAt      time.Time      `json:"created_at"`
	LastActiveAt   sql.NullTime   `json:"last_active_at"`
}

type ChatroomMember struct {
	MemberRelID   string           `json:"member_rel_id"`
	UserID        string           `json:"user_id"`
	RoomID        string           `json:"room_id"`
	JoinedAt      time.Time        `json:"joined_at"`
	LeftAt        sql.NullTime     `json:"left_at"`
	LastReadAt    sql.NullTime     `json:"last_read_at"`
	MemberRole    MemberRole       `json:"member_role"`
	MuteStatus    MemberMuteStatus `json:"mute_status"`
	MuteExpiresAt sql.NullTime     `json:"mute_expires_at"`
	IsActive      bool             `json:"is_active"`
}

type GlobalMuteRecord struct {
	GlobalMuteID string         `json:"global_mute_id"`
	MutedUserID  string         `json:"muted_user_id"`
	StartAt      time.Time      `json:"start_at"`
	ExpiresAt    time.Time      `json:"expires_at"`
	Reason       sql.NullString `json:"reason"`
	IsActive     bool           `json:"is_active"`
	AdminID      sql.NullString `json:"admin_id"`
}

type Message struct {
	MessageID       string         `json:"message_id"`
	SentAt          time.Time      `json:"sent_at"`
	Content         string         `json:"content"`
	MessageType     MessageType    `json:"message_type"`
	QuotedMessageID sql.NullString `json:"quoted_message_id"`
	SenderID        sql.NullString `json:"sender_id"`
	RoomID          string         `json:"room_id"`
}

type MuteRecord struct {
	MuteRecordID string         `json:"mute_record_id"`
	MemberRelID  string         `json:"member_rel_id"`
	StartAt      time.Time      `json:"start_at"`
	ExpiresAt    time.Time      `json:"expires_at"`
	Reason       sql.NullString `json:"reason"`
	IsActive     bool           `json:"is_active"`
	AdminID      sql.NullString `json:"admin_id"`
}

type User struct {
	UserID         string                `json:"user_id"`
	Username       string                `json:"username"`
	HashedPassword string                `json:"hashed_password"`
	Nickname       sql.NullString        `json:"nickname"`
	PhoneNumber    sql.NullString        `json:"phone_number"`
	Email          sql.NullString        `json:"email"`
	AvatarUrl      sql.NullString        `json:"avatar_url"`
	Bio            sql.NullString        `json:"bio"`
	OnlineStatus   NullUserOnlineStatus  `json:"online_status"`
	AccountStatus  NullUserAccountStatus `json:"account_status"`
	SystemRole     NullUserSystemRole    `json:"system_role"`
	RegisteredAt   time.Time             `json:"registered_at"`
	LastLoginAt    sql.NullTime          `json:"last_login_at"`
}
