// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mute_record.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const canUserSendMessageInRoom = `-- name: CanUserSendMessageInRoom :one

SELECT 
    NOT EXISTS(
        SELECT 1 FROM global_mute_records 
        WHERE muted_user_id = $1 
            AND is_active = true 
            AND (expires_at IS NULL OR expires_at > NOW())
    )
    AND NOT EXISTS(
        SELECT 1 FROM mute_records mr
        JOIN chatroom_members cm ON mr.member_rel_id = cm.member_rel_id
        WHERE cm.user_id = $1 
            AND cm.room_id = $2 
            AND mr.is_active = true 
            AND (mr.expires_at IS NULL OR mr.expires_at > NOW())
    ) AS can_send
`

type CanUserSendMessageInRoomParams struct {
	MutedUserID string `json:"muted_user_id"`
	RoomID      string `json:"room_id"`
}

// =============================================
// 3. 综合禁言检查 (Combined Mute Checks)
// =============================================
// 检查用户是否可以在聊天室发送消息（综合检查全局禁言和聊天室禁言）
func (q *Queries) CanUserSendMessageInRoom(ctx context.Context, arg CanUserSendMessageInRoomParams) (sql.NullBool, error) {
	row := q.queryRow(ctx, q.canUserSendMessageInRoomStmt, canUserSendMessageInRoom, arg.MutedUserID, arg.RoomID)
	var can_send sql.NullBool
	err := row.Scan(&can_send)
	return can_send, err
}

const createGlobalMuteRecord = `-- name: CreateGlobalMuteRecord :one

INSERT INTO global_mute_records (
    muted_user_id,
    expires_at,
    reason,
    admin_id
) VALUES (
    $1, $2, $3, $4
) RETURNING 
    global_mute_id,
    muted_user_id,
    start_at,
    expires_at,
    reason,
    is_active,
    admin_id
`

type CreateGlobalMuteRecordParams struct {
	MutedUserID string         `json:"muted_user_id"`
	ExpiresAt   time.Time      `json:"expires_at"`
	Reason      sql.NullString `json:"reason"`
	AdminID     sql.NullString `json:"admin_id"`
}

// =============================================
// 2. 全局禁言记录 (Global Mute Records)
// =============================================
// 创建全局禁言记录（超级管理员操作）
func (q *Queries) CreateGlobalMuteRecord(ctx context.Context, arg CreateGlobalMuteRecordParams) (GlobalMuteRecord, error) {
	row := q.queryRow(ctx, q.createGlobalMuteRecordStmt, createGlobalMuteRecord,
		arg.MutedUserID,
		arg.ExpiresAt,
		arg.Reason,
		arg.AdminID,
	)
	var i GlobalMuteRecord
	err := row.Scan(
		&i.GlobalMuteID,
		&i.MutedUserID,
		&i.StartAt,
		&i.ExpiresAt,
		&i.Reason,
		&i.IsActive,
		&i.AdminID,
	)
	return i, err
}

const createMuteRecord = `-- name: CreateMuteRecord :one


INSERT INTO mute_records (
    member_rel_id,
    expires_at,
    reason,
    admin_id
) VALUES (
    $1, $2, $3, $4
) RETURNING 
    mute_record_id,
    member_rel_id,
    start_at,
    expires_at,
    reason,
    is_active,
    admin_id
`

type CreateMuteRecordParams struct {
	MemberRelID string         `json:"member_rel_id"`
	ExpiresAt   time.Time      `json:"expires_at"`
	Reason      sql.NullString `json:"reason"`
	AdminID     sql.NullString `json:"admin_id"`
}

// =============================================
// 禁言记录相关SQL查询 (Mute Record Queries)
// 对应API: 聊天室成员管理接口 - 禁言功能
// =============================================
// =============================================
// 1. 聊天室禁言记录 (Room Mute Records)
// =============================================
// 创建禁言记录 POST /chatrooms/:roomId/members/:userId/mute
func (q *Queries) CreateMuteRecord(ctx context.Context, arg CreateMuteRecordParams) (MuteRecord, error) {
	row := q.queryRow(ctx, q.createMuteRecordStmt, createMuteRecord,
		arg.MemberRelID,
		arg.ExpiresAt,
		arg.Reason,
		arg.AdminID,
	)
	var i MuteRecord
	err := row.Scan(
		&i.MuteRecordID,
		&i.MemberRelID,
		&i.StartAt,
		&i.ExpiresAt,
		&i.Reason,
		&i.IsActive,
		&i.AdminID,
	)
	return i, err
}

const deactivateGlobalMuteRecord = `-- name: DeactivateGlobalMuteRecord :exec
UPDATE global_mute_records 
SET is_active = false
WHERE muted_user_id = $1 AND is_active = true
`

// 解除全局禁言
func (q *Queries) DeactivateGlobalMuteRecord(ctx context.Context, mutedUserID string) error {
	_, err := q.exec(ctx, q.deactivateGlobalMuteRecordStmt, deactivateGlobalMuteRecord, mutedUserID)
	return err
}

const deactivateGlobalMuteRecordByID = `-- name: DeactivateGlobalMuteRecordByID :exec
UPDATE global_mute_records 
SET is_active = false
WHERE global_mute_id = $1
`

// 通过ID解除全局禁言
func (q *Queries) DeactivateGlobalMuteRecordByID(ctx context.Context, globalMuteID string) error {
	_, err := q.exec(ctx, q.deactivateGlobalMuteRecordByIDStmt, deactivateGlobalMuteRecordByID, globalMuteID)
	return err
}

const deactivateMuteRecord = `-- name: DeactivateMuteRecord :exec
UPDATE mute_records 
SET is_active = false
WHERE member_rel_id = $1 AND is_active = true
`

// 解除禁言（使禁言记录失效）POST /chatrooms/:roomId/members/:userId/unmute
func (q *Queries) DeactivateMuteRecord(ctx context.Context, memberRelID string) error {
	_, err := q.exec(ctx, q.deactivateMuteRecordStmt, deactivateMuteRecord, memberRelID)
	return err
}

const deactivateMuteRecordByID = `-- name: DeactivateMuteRecordByID :exec
UPDATE mute_records 
SET is_active = false
WHERE mute_record_id = $1
`

// 通过ID解除禁言
func (q *Queries) DeactivateMuteRecordByID(ctx context.Context, muteRecordID string) error {
	_, err := q.exec(ctx, q.deactivateMuteRecordByIDStmt, deactivateMuteRecordByID, muteRecordID)
	return err
}

const expireGlobalMuteRecords = `-- name: ExpireGlobalMuteRecords :exec
UPDATE global_mute_records 
SET is_active = false
WHERE is_active = true AND expires_at IS NOT NULL AND expires_at <= NOW()
`

// 批量过期全局禁言记录
func (q *Queries) ExpireGlobalMuteRecords(ctx context.Context) error {
	_, err := q.exec(ctx, q.expireGlobalMuteRecordsStmt, expireGlobalMuteRecords)
	return err
}

const expireMuteRecords = `-- name: ExpireMuteRecords :exec
UPDATE mute_records 
SET is_active = false
WHERE is_active = true AND expires_at IS NOT NULL AND expires_at <= NOW()
`

// 批量过期禁言记录
func (q *Queries) ExpireMuteRecords(ctx context.Context) error {
	_, err := q.exec(ctx, q.expireMuteRecordsStmt, expireMuteRecords)
	return err
}

const getActiveGlobalMuteRecord = `-- name: GetActiveGlobalMuteRecord :one
SELECT 
    global_mute_id,
    muted_user_id,
    start_at,
    expires_at,
    reason,
    is_active,
    admin_id
FROM global_mute_records 
WHERE muted_user_id = $1 
    AND is_active = true 
    AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY start_at DESC
LIMIT 1
`

// 获取用户当前有效的全局禁言记录
func (q *Queries) GetActiveGlobalMuteRecord(ctx context.Context, mutedUserID string) (GlobalMuteRecord, error) {
	row := q.queryRow(ctx, q.getActiveGlobalMuteRecordStmt, getActiveGlobalMuteRecord, mutedUserID)
	var i GlobalMuteRecord
	err := row.Scan(
		&i.GlobalMuteID,
		&i.MutedUserID,
		&i.StartAt,
		&i.ExpiresAt,
		&i.Reason,
		&i.IsActive,
		&i.AdminID,
	)
	return i, err
}

const getActiveMuteRecord = `-- name: GetActiveMuteRecord :one
SELECT 
    mute_record_id,
    member_rel_id,
    start_at,
    expires_at,
    reason,
    is_active,
    admin_id
FROM mute_records 
WHERE member_rel_id = $1 
    AND is_active = true 
    AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY start_at DESC
LIMIT 1
`

// 获取成员当前有效的禁言记录
func (q *Queries) GetActiveMuteRecord(ctx context.Context, memberRelID string) (MuteRecord, error) {
	row := q.queryRow(ctx, q.getActiveMuteRecordStmt, getActiveMuteRecord, memberRelID)
	var i MuteRecord
	err := row.Scan(
		&i.MuteRecordID,
		&i.MemberRelID,
		&i.StartAt,
		&i.ExpiresAt,
		&i.Reason,
		&i.IsActive,
		&i.AdminID,
	)
	return i, err
}

const getActiveMuteRecordsByRoom = `-- name: GetActiveMuteRecordsByRoom :many
SELECT 
    mr.mute_record_id,
    mr.member_rel_id,
    mr.start_at,
    mr.expires_at,
    mr.reason,
    mr.is_active,
    mr.admin_id,
    cm.user_id,
    u.username,
    u.nickname,
    u.avatar_url
FROM mute_records mr
JOIN chatroom_members cm ON mr.member_rel_id = cm.member_rel_id
JOIN users u ON cm.user_id = u.user_id
WHERE cm.room_id = $1 
    AND mr.is_active = true 
    AND (mr.expires_at IS NULL OR mr.expires_at > NOW())
ORDER BY mr.expires_at ASC NULLS LAST
`

type GetActiveMuteRecordsByRoomRow struct {
	MuteRecordID string         `json:"mute_record_id"`
	MemberRelID  string         `json:"member_rel_id"`
	StartAt      time.Time      `json:"start_at"`
	ExpiresAt    time.Time      `json:"expires_at"`
	Reason       sql.NullString `json:"reason"`
	IsActive     bool           `json:"is_active"`
	AdminID      sql.NullString `json:"admin_id"`
	UserID       string         `json:"user_id"`
	Username     string         `json:"username"`
	Nickname     sql.NullString `json:"nickname"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
}

// 获取聊天室当前有效的禁言记录
func (q *Queries) GetActiveMuteRecordsByRoom(ctx context.Context, roomID string) ([]GetActiveMuteRecordsByRoomRow, error) {
	rows, err := q.query(ctx, q.getActiveMuteRecordsByRoomStmt, getActiveMuteRecordsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveMuteRecordsByRoomRow{}
	for rows.Next() {
		var i GetActiveMuteRecordsByRoomRow
		if err := rows.Scan(
			&i.MuteRecordID,
			&i.MemberRelID,
			&i.StartAt,
			&i.ExpiresAt,
			&i.Reason,
			&i.IsActive,
			&i.AdminID,
			&i.UserID,
			&i.Username,
			&i.Nickname,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllActiveGlobalMuteRecords = `-- name: GetAllActiveGlobalMuteRecords :many
SELECT 
    gmr.global_mute_id,
    gmr.muted_user_id,
    gmr.start_at,
    gmr.expires_at,
    gmr.reason,
    gmr.is_active,
    gmr.admin_id,
    u.username,
    u.nickname,
    u.avatar_url
FROM global_mute_records gmr
JOIN users u ON gmr.muted_user_id = u.user_id
WHERE gmr.is_active = true 
    AND (gmr.expires_at IS NULL OR gmr.expires_at > NOW())
ORDER BY gmr.expires_at ASC NULLS LAST
LIMIT $1 OFFSET $2
`

type GetAllActiveGlobalMuteRecordsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type GetAllActiveGlobalMuteRecordsRow struct {
	GlobalMuteID string         `json:"global_mute_id"`
	MutedUserID  string         `json:"muted_user_id"`
	StartAt      time.Time      `json:"start_at"`
	ExpiresAt    time.Time      `json:"expires_at"`
	Reason       sql.NullString `json:"reason"`
	IsActive     bool           `json:"is_active"`
	AdminID      sql.NullString `json:"admin_id"`
	Username     string         `json:"username"`
	Nickname     sql.NullString `json:"nickname"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
}

// 获取所有有效的全局禁言记录
func (q *Queries) GetAllActiveGlobalMuteRecords(ctx context.Context, arg GetAllActiveGlobalMuteRecordsParams) ([]GetAllActiveGlobalMuteRecordsRow, error) {
	rows, err := q.query(ctx, q.getAllActiveGlobalMuteRecordsStmt, getAllActiveGlobalMuteRecords, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllActiveGlobalMuteRecordsRow{}
	for rows.Next() {
		var i GetAllActiveGlobalMuteRecordsRow
		if err := rows.Scan(
			&i.GlobalMuteID,
			&i.MutedUserID,
			&i.StartAt,
			&i.ExpiresAt,
			&i.Reason,
			&i.IsActive,
			&i.AdminID,
			&i.Username,
			&i.Nickname,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalMuteRecordByID = `-- name: GetGlobalMuteRecordByID :one
SELECT 
    global_mute_id,
    muted_user_id,
    start_at,
    expires_at,
    reason,
    is_active,
    admin_id
FROM global_mute_records 
WHERE global_mute_id = $1
`

// 获取全局禁言记录
func (q *Queries) GetGlobalMuteRecordByID(ctx context.Context, globalMuteID string) (GlobalMuteRecord, error) {
	row := q.queryRow(ctx, q.getGlobalMuteRecordByIDStmt, getGlobalMuteRecordByID, globalMuteID)
	var i GlobalMuteRecord
	err := row.Scan(
		&i.GlobalMuteID,
		&i.MutedUserID,
		&i.StartAt,
		&i.ExpiresAt,
		&i.Reason,
		&i.IsActive,
		&i.AdminID,
	)
	return i, err
}

const getGlobalMuteRecordsByUser = `-- name: GetGlobalMuteRecordsByUser :many
SELECT 
    global_mute_id,
    muted_user_id,
    start_at,
    expires_at,
    reason,
    is_active,
    admin_id
FROM global_mute_records 
WHERE muted_user_id = $1
ORDER BY start_at DESC
LIMIT $2 OFFSET $3
`

type GetGlobalMuteRecordsByUserParams struct {
	MutedUserID string `json:"muted_user_id"`
	Limit       int64  `json:"limit"`
	Offset      int64  `json:"offset"`
}

// 获取用户的所有全局禁言记录
func (q *Queries) GetGlobalMuteRecordsByUser(ctx context.Context, arg GetGlobalMuteRecordsByUserParams) ([]GlobalMuteRecord, error) {
	rows, err := q.query(ctx, q.getGlobalMuteRecordsByUserStmt, getGlobalMuteRecordsByUser, arg.MutedUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlobalMuteRecord{}
	for rows.Next() {
		var i GlobalMuteRecord
		if err := rows.Scan(
			&i.GlobalMuteID,
			&i.MutedUserID,
			&i.StartAt,
			&i.ExpiresAt,
			&i.Reason,
			&i.IsActive,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberMuteExpireTime = `-- name: GetMemberMuteExpireTime :one
SELECT mr.expires_at
FROM mute_records mr
JOIN chatroom_members cm ON mr.member_rel_id = cm.member_rel_id
WHERE cm.user_id = $1 
    AND cm.room_id = $2 
    AND mr.is_active = true 
    AND (mr.expires_at IS NULL OR mr.expires_at > NOW())
ORDER BY mr.expires_at DESC NULLS FIRST
LIMIT 1
`

type GetMemberMuteExpireTimeParams struct {
	UserID string `json:"user_id"`
	RoomID string `json:"room_id"`
}

// 获取成员禁言到期时间
func (q *Queries) GetMemberMuteExpireTime(ctx context.Context, arg GetMemberMuteExpireTimeParams) (time.Time, error) {
	row := q.queryRow(ctx, q.getMemberMuteExpireTimeStmt, getMemberMuteExpireTime, arg.UserID, arg.RoomID)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const getMuteRecordByID = `-- name: GetMuteRecordByID :one
SELECT 
    mute_record_id,
    member_rel_id,
    start_at,
    expires_at,
    reason,
    is_active,
    admin_id
FROM mute_records 
WHERE mute_record_id = $1
`

// 获取禁言记录
func (q *Queries) GetMuteRecordByID(ctx context.Context, muteRecordID string) (MuteRecord, error) {
	row := q.queryRow(ctx, q.getMuteRecordByIDStmt, getMuteRecordByID, muteRecordID)
	var i MuteRecord
	err := row.Scan(
		&i.MuteRecordID,
		&i.MemberRelID,
		&i.StartAt,
		&i.ExpiresAt,
		&i.Reason,
		&i.IsActive,
		&i.AdminID,
	)
	return i, err
}

const getMuteRecordsByMember = `-- name: GetMuteRecordsByMember :many
SELECT 
    mute_record_id,
    member_rel_id,
    start_at,
    expires_at,
    reason,
    is_active,
    admin_id
FROM mute_records 
WHERE member_rel_id = $1
ORDER BY start_at DESC
LIMIT $2 OFFSET $3
`

type GetMuteRecordsByMemberParams struct {
	MemberRelID string `json:"member_rel_id"`
	Limit       int64  `json:"limit"`
	Offset      int64  `json:"offset"`
}

// 获取成员的所有禁言记录
func (q *Queries) GetMuteRecordsByMember(ctx context.Context, arg GetMuteRecordsByMemberParams) ([]MuteRecord, error) {
	rows, err := q.query(ctx, q.getMuteRecordsByMemberStmt, getMuteRecordsByMember, arg.MemberRelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MuteRecord{}
	for rows.Next() {
		var i MuteRecord
		if err := rows.Scan(
			&i.MuteRecordID,
			&i.MemberRelID,
			&i.StartAt,
			&i.ExpiresAt,
			&i.Reason,
			&i.IsActive,
			&i.AdminID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMuteRecordsByRoom = `-- name: GetMuteRecordsByRoom :many
SELECT 
    mr.mute_record_id,
    mr.member_rel_id,
    mr.start_at,
    mr.expires_at,
    mr.reason,
    mr.is_active,
    mr.admin_id,
    cm.user_id,
    cm.room_id,
    u.username,
    u.nickname
FROM mute_records mr
JOIN chatroom_members cm ON mr.member_rel_id = cm.member_rel_id
JOIN users u ON cm.user_id = u.user_id
WHERE cm.room_id = $1
ORDER BY mr.start_at DESC
LIMIT $2 OFFSET $3
`

type GetMuteRecordsByRoomParams struct {
	RoomID string `json:"room_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type GetMuteRecordsByRoomRow struct {
	MuteRecordID string         `json:"mute_record_id"`
	MemberRelID  string         `json:"member_rel_id"`
	StartAt      time.Time      `json:"start_at"`
	ExpiresAt    time.Time      `json:"expires_at"`
	Reason       sql.NullString `json:"reason"`
	IsActive     bool           `json:"is_active"`
	AdminID      sql.NullString `json:"admin_id"`
	UserID       string         `json:"user_id"`
	RoomID       string         `json:"room_id"`
	Username     string         `json:"username"`
	Nickname     sql.NullString `json:"nickname"`
}

// 获取聊天室的所有禁言记录
func (q *Queries) GetMuteRecordsByRoom(ctx context.Context, arg GetMuteRecordsByRoomParams) ([]GetMuteRecordsByRoomRow, error) {
	rows, err := q.query(ctx, q.getMuteRecordsByRoomStmt, getMuteRecordsByRoom, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMuteRecordsByRoomRow{}
	for rows.Next() {
		var i GetMuteRecordsByRoomRow
		if err := rows.Scan(
			&i.MuteRecordID,
			&i.MemberRelID,
			&i.StartAt,
			&i.ExpiresAt,
			&i.Reason,
			&i.IsActive,
			&i.AdminID,
			&i.UserID,
			&i.RoomID,
			&i.Username,
			&i.Nickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGlobalMuteExpireTime = `-- name: GetUserGlobalMuteExpireTime :one
SELECT expires_at
FROM global_mute_records 
WHERE muted_user_id = $1 
    AND is_active = true 
    AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY expires_at DESC NULLS FIRST
LIMIT 1
`

// 获取用户全局禁言到期时间
func (q *Queries) GetUserGlobalMuteExpireTime(ctx context.Context, mutedUserID string) (time.Time, error) {
	row := q.queryRow(ctx, q.getUserGlobalMuteExpireTimeStmt, getUserGlobalMuteExpireTime, mutedUserID)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const getUserMuteStatus = `-- name: GetUserMuteStatus :one
SELECT 
    EXISTS(
        SELECT 1 FROM global_mute_records 
        WHERE muted_user_id = $1 
            AND is_active = true 
            AND (expires_at IS NULL OR expires_at > NOW())
    ) AS is_globally_muted,
    EXISTS(
        SELECT 1 FROM mute_records mr
        JOIN chatroom_members cm ON mr.member_rel_id = cm.member_rel_id
        WHERE cm.user_id = $1 
            AND cm.room_id = $2 
            AND mr.is_active = true 
            AND (mr.expires_at IS NULL OR mr.expires_at > NOW())
    ) AS is_room_muted
`

type GetUserMuteStatusParams struct {
	MutedUserID string `json:"muted_user_id"`
	RoomID      string `json:"room_id"`
}

type GetUserMuteStatusRow struct {
	IsGloballyMuted bool `json:"is_globally_muted"`
	IsRoomMuted     bool `json:"is_room_muted"`
}

// 获取用户的禁言状态（返回全局禁言和聊天室禁言状态）
func (q *Queries) GetUserMuteStatus(ctx context.Context, arg GetUserMuteStatusParams) (GetUserMuteStatusRow, error) {
	row := q.queryRow(ctx, q.getUserMuteStatusStmt, getUserMuteStatus, arg.MutedUserID, arg.RoomID)
	var i GetUserMuteStatusRow
	err := row.Scan(&i.IsGloballyMuted, &i.IsRoomMuted)
	return i, err
}

const isMemberMutedInRoom = `-- name: IsMemberMutedInRoom :one
SELECT EXISTS(
    SELECT 1 FROM mute_records mr
    JOIN chatroom_members cm ON mr.member_rel_id = cm.member_rel_id
    WHERE cm.user_id = $1 
        AND cm.room_id = $2 
        AND mr.is_active = true 
        AND (mr.expires_at IS NULL OR mr.expires_at > NOW())
) AS is_muted
`

type IsMemberMutedInRoomParams struct {
	UserID string `json:"user_id"`
	RoomID string `json:"room_id"`
}

// 检查成员在聊天室是否被禁言
func (q *Queries) IsMemberMutedInRoom(ctx context.Context, arg IsMemberMutedInRoomParams) (bool, error) {
	row := q.queryRow(ctx, q.isMemberMutedInRoomStmt, isMemberMutedInRoom, arg.UserID, arg.RoomID)
	var is_muted bool
	err := row.Scan(&is_muted)
	return is_muted, err
}

const isUserGloballyMuted = `-- name: IsUserGloballyMuted :one
SELECT EXISTS(
    SELECT 1 FROM global_mute_records 
    WHERE muted_user_id = $1 
        AND is_active = true 
        AND (expires_at IS NULL OR expires_at > NOW())
) AS is_globally_muted
`

// 检查用户是否被全局禁言
func (q *Queries) IsUserGloballyMuted(ctx context.Context, mutedUserID string) (bool, error) {
	row := q.queryRow(ctx, q.isUserGloballyMutedStmt, isUserGloballyMuted, mutedUserID)
	var is_globally_muted bool
	err := row.Scan(&is_globally_muted)
	return is_globally_muted, err
}
