// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"
)

type Querier interface {
	CountChatroomMembers(ctx context.Context, roomID string) (int64, error)
	CountUserChatrooms(ctx context.Context, userID string) (int64, error)
	CreateChatroom(ctx context.Context, arg CreateChatroomParams) (Chatroom, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecrementChatroomMemberCount(ctx context.Context, roomID string) error
	DecrementChatroomOnlineCount(ctx context.Context, roomID string) error
	DeleteChatroom(ctx context.Context, roomID string) error
	DeleteMessage(ctx context.Context, messageID string) error
	GetChatroomByID(ctx context.Context, roomID string) (Chatroom, error)
	GetChatroomMembers(ctx context.Context, arg GetChatroomMembersParams) ([]GetChatroomMembersRow, error)
	GetMessageByID(ctx context.Context, messageID string) (Message, error)
	GetMessagesByRoom(ctx context.Context, arg GetMessagesByRoomParams) ([]Message, error)
	GetUnreadMessageCount(ctx context.Context, arg GetUnreadMessageCountParams) (int64, error)
	GetUserByID(ctx context.Context, userID string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserChatroomMembership(ctx context.Context, arg GetUserChatroomMembershipParams) (ChatroomMember, error)
	IncrementChatroomMemberCount(ctx context.Context, roomID string) error
	IncrementChatroomOnlineCount(ctx context.Context, roomID string) error
	IsMemberMuted(ctx context.Context, arg IsMemberMutedParams) (bool, error)
	JoinChatroom(ctx context.Context, arg JoinChatroomParams) (ChatroomMember, error)
	LeaveChatroom(ctx context.Context, arg LeaveChatroomParams) error
	ListUserChatrooms(ctx context.Context, arg ListUserChatroomsParams) ([]ListUserChatroomsRow, error)
	MuteMember(ctx context.Context, arg MuteMemberParams) error
	SetMemberRole(ctx context.Context, arg SetMemberRoleParams) error
	UnmuteMember(ctx context.Context, arg UnmuteMemberParams) error
	UpdateChatroom(ctx context.Context, arg UpdateChatroomParams) (Chatroom, error)
	UpdateChatroomLastActiveTime(ctx context.Context, roomID string) error
	UpdateMemberLastReadTime(ctx context.Context, arg UpdateMemberLastReadTimeParams) error
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
