// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    hashed_password,
    nickname,
    phone_number,
    email,
    avatar_url,
    bio
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING 
    user_id,
    username,
    hashed_password,
    nickname,
    phone_number,
    email,
    avatar_url,
    bio,
    online_status,
    account_status,
    system_role,
    registered_at,
    last_login_at
`

type CreateUserParams struct {
	Username       string         `json:"username"`
	HashedPassword string         `json:"hashed_password"`
	Nickname       sql.NullString `json:"nickname"`
	PhoneNumber    sql.NullString `json:"phone_number"`
	Email          sql.NullString `json:"email"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	Bio            sql.NullString `json:"bio"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Username,
		arg.HashedPassword,
		arg.Nickname,
		arg.PhoneNumber,
		arg.Email,
		arg.AvatarUrl,
		arg.Bio,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.HashedPassword,
		&i.Nickname,
		&i.PhoneNumber,
		&i.Email,
		&i.AvatarUrl,
		&i.Bio,
		&i.OnlineStatus,
		&i.AccountStatus,
		&i.SystemRole,
		&i.RegisteredAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
    user_id,
    username,
    hashed_password,
    nickname,
    phone_number,
    email,
    avatar_url,
    bio,
    online_status,
    account_status,
    system_role,
    registered_at,
    last_login_at
FROM users 
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID string) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.HashedPassword,
		&i.Nickname,
		&i.PhoneNumber,
		&i.Email,
		&i.AvatarUrl,
		&i.Bio,
		&i.OnlineStatus,
		&i.AccountStatus,
		&i.SystemRole,
		&i.RegisteredAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT 
    user_id,
    username,
    hashed_password,
    nickname,
    phone_number,
    email,
    avatar_url,
    bio,
    online_status,
    account_status,
    system_role,
    registered_at,
    last_login_at
FROM users 
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.HashedPassword,
		&i.Nickname,
		&i.PhoneNumber,
		&i.Email,
		&i.AvatarUrl,
		&i.Bio,
		&i.OnlineStatus,
		&i.AccountStatus,
		&i.SystemRole,
		&i.RegisteredAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET 
    nickname = $2,
    phone_number = $3,
    email = $4,
    avatar_url = $5,
    bio = $6,
    online_status = $7,
    last_login_at = $8
WHERE user_id = $1
RETURNING 
    user_id,
    username,
    hashed_password,
    nickname,
    phone_number,
    email,
    avatar_url,
    bio,
    online_status,
    account_status,
    system_role,
    registered_at,
    last_login_at
`

type UpdateUserParams struct {
	UserID       string               `json:"user_id"`
	Nickname     sql.NullString       `json:"nickname"`
	PhoneNumber  sql.NullString       `json:"phone_number"`
	Email        sql.NullString       `json:"email"`
	AvatarUrl    sql.NullString       `json:"avatar_url"`
	Bio          sql.NullString       `json:"bio"`
	OnlineStatus NullUserOnlineStatus `json:"online_status"`
	LastLoginAt  sql.NullTime         `json:"last_login_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserStmt, updateUser,
		arg.UserID,
		arg.Nickname,
		arg.PhoneNumber,
		arg.Email,
		arg.AvatarUrl,
		arg.Bio,
		arg.OnlineStatus,
		arg.LastLoginAt,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.HashedPassword,
		&i.Nickname,
		&i.PhoneNumber,
		&i.Email,
		&i.AvatarUrl,
		&i.Bio,
		&i.OnlineStatus,
		&i.AccountStatus,
		&i.SystemRole,
		&i.RegisteredAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users 
SET hashed_password = $2
WHERE user_id = $1
`

type UpdateUserPasswordParams struct {
	UserID         string `json:"user_id"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.exec(ctx, q.updateUserPasswordStmt, updateUserPassword, arg.UserID, arg.HashedPassword)
	return err
}
